import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:svid/core/auth/domain/entities/platform_cookie.dart';
import 'package:svid/core/config/brand_config.dart';
import 'package:svid/core/logging/app_logger.dart';

/// Exports app cookies to Netscape format for yt-dlp consumption
class CookieExporter {
  static String get _header =>
      '# Netscape HTTP Cookie File\n'
      '# https://curl.haxx.se/docs/http-cookies.html\n'
      '# This file was generated by ${BrandConfig.current.appName}. Do not edit.\n\n';

  /// Map of platform names to their cookie domains
  static const _platformDomains = {
    'youtube': '.youtube.com',
    'tiktok': '.tiktok.com',
    'instagram': '.instagram.com',
    'facebook': '.facebook.com',
    'twitter': '.twitter.com',
    'x': '.x.com',
    'reddit': '.reddit.com',
    'pinterest': '.pinterest.com',
    'douyin': '.douyin.com',
  };

  /// Export cookies to a temporary file in Netscape format
  /// Returns the path to the temporary file
  Future<String> exportToFile(List<PlatformCookie> cookies) async {
    final tempDir = await getTemporaryDirectory();
    final fileName =
        'ytdlp_cookies_${DateTime.now().microsecondsSinceEpoch}.txt';
    final filePath = path.join(tempDir.path, fileName);

    final content = _convertToNetscape(cookies);
    await File(filePath).writeAsString(content);

    return filePath;
  }

  /// Export a single platform's cookies to a temporary file
  Future<String> exportPlatformCookies(PlatformCookie cookie) async {
    final tempDir = await getTemporaryDirectory();
    final fileName = 'ytdlp_cookies_${cookie.platform}.txt';
    final filePath = path.join(tempDir.path, fileName);

    String content;

    // Check if cookieString is already in Netscape format
    // Netscape format has tab-separated fields, typically 7 per line
    if (_isNetscapeFormat(cookie.cookieString)) {
      // Already Netscape format - ensure it has the header
      final normalized = _normalizeNetscapeCookieExpirations(
        cookie.cookieString,
      );
      if (normalized.trimLeft().startsWith('#')) {
        content = normalized;
      } else {
        content = '$_header$normalized';
      }
    } else {
      // Legacy format (name=value; name2=value2) - convert to Netscape
      final cookieLines = _convertCookieStringToNetscape(
        cookie.platform,
        cookie.cookieString,
        cookie.expiresAt,
      );
      content = '$_header$cookieLines';
    }

    await File(filePath).writeAsString(content);
    appLogger.info(
      '[Cookies] Exported ${_countNetscapeCookieLines(content)} '
      '${cookie.platform} cookies '
      '(${_countAuthCookieLines(content)} auth markers) to $filePath',
    );
    return filePath;
  }

  /// Check if a cookie string is in Netscape format
  /// Netscape format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
  bool _isNetscapeFormat(String cookieString) {
    final lines = cookieString.split('\n');
    for (final line in lines) {
      final trimmed = line.trim();
      // Skip empty lines and comments
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;

      // Netscape format has 7 tab-separated fields
      final fields = trimmed.split('\t');
      if (fields.length >= 6) {
        // Looks like Netscape format
        return true;
      }
      // If first non-comment line doesn't look like Netscape, it's not
      return false;
    }
    return false;
  }

  int _countNetscapeCookieLines(String content) {
    return content.split('\n').where((line) {
      final trimmed = line.trim();
      return trimmed.isNotEmpty &&
          !trimmed.startsWith('#') &&
          trimmed.split('\t').length >= 7;
    }).length;
  }

  int _countAuthCookieLines(String content) {
    const authCookieNames = {
      'SID',
      'HSID',
      'SSID',
      'APISID',
      'SAPISID',
      'LOGIN_INFO',
      'LSID',
      '__Secure-1PSID',
      '__Secure-3PSID',
      '__Secure-1PSIDTS',
      '__Secure-3PSIDTS',
      '__Host-1PLSID',
      '__Host-3PLSID',
      '__Host-GAPS',
      '__Host-GAPSTS',
    };

    var count = 0;
    for (final line in content.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final fields = trimmed.split('\t');
      if (fields.length >= 7 && authCookieNames.contains(fields[5])) {
        count++;
      }
    }
    return count;
  }

  /// Repair old Windows WebView2 exports that stored cookie expiry as 1970.
  ///
  /// The affected code interpreted WebView2's Unix-seconds `expiresDate` as
  /// milliseconds. A real 2027 expiry like `1813223000` was written back as
  /// `1813223`, so yt-dlp silently discarded the auth cookies as expired.
  /// Normalize those legacy Netscape lines at export time so users do not need
  /// to delete the app or re-login just to repair the persisted cookie record.
  String _normalizeNetscapeCookieExpirations(String content) {
    const jan2000 = 946684800;
    final lines = content.split('\n');
    var changed = false;

    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;

      final fields = line.split('\t');
      if (fields.length < 7) continue;

      final expiry = int.tryParse(fields[4]);
      if (expiry == null || expiry == 0 || expiry >= jan2000) continue;

      fields[4] = (expiry * 1000).toString();
      lines[i] = fields.join('\t');
      changed = true;
    }

    if (changed) {
      appLogger.warning(
        '[Cookies] Repaired legacy Netscape cookie expirations that were '
        'written as 1970-era seconds.',
      );
    }

    return lines.join('\n');
  }

  /// Convert cookies to Netscape format string
  String _convertToNetscape(List<PlatformCookie> cookies) {
    final buffer = StringBuffer(_header);

    for (final cookie in cookies) {
      buffer.write(
        _convertCookieStringToNetscape(
          cookie.platform,
          cookie.cookieString,
          cookie.expiresAt,
        ),
      );
    }

    return buffer.toString();
  }

  /// Convert a cookie string to Netscape format
  /// Cookie string format: "name1=value1; name2=value2; ..."
  String _convertCookieStringToNetscape(
    String platform,
    String cookieString,
    DateTime? expiresAt,
  ) {
    final domain = _platformDomains[platform.toLowerCase()] ?? '.$platform.com';
    final buffer = StringBuffer();

    // Parse cookie string into individual cookies
    final cookieParts = cookieString.split(';');

    for (final part in cookieParts) {
      final trimmed = part.trim();
      if (trimmed.isEmpty) continue;

      final equalsIndex = trimmed.indexOf('=');
      if (equalsIndex == -1) continue;

      final name = trimmed.substring(0, equalsIndex).trim();
      final value = trimmed.substring(equalsIndex + 1).trim();

      if (name.isEmpty || value.isEmpty) continue;

      // Netscape format:
      // domain  flag  path  secure  expiration  name  value
      // .example.com  TRUE  /  TRUE  1234567890  cookie_name  cookie_value

      final includeSubdomains = 'TRUE';
      final cookiePath = '/';
      // All major platforms are HTTPS-only — cookies must be marked secure
      // or gallery-dl/yt-dlp won't send them on HTTPS connections
      final isSecure = 'TRUE';
      final expiration =
          expiresAt != null
              ? (expiresAt.millisecondsSinceEpoch ~/ 1000)
              : (DateTime.now()
                      .add(const Duration(days: 365))
                      .millisecondsSinceEpoch ~/
                  1000);

      buffer.writeln(
        '$domain\t$includeSubdomains\t$cookiePath\t$isSecure\t$expiration\t$name\t$value',
      );
    }

    return buffer.toString();
  }

  /// Delete a temporary cookie file
  Future<void> deleteCookieFile(String filePath) async {
    try {
      final file = File(filePath);
      if (await file.exists()) {
        await file.delete();
      }
    } catch (_) {
      // Ignore deletion errors
    }
  }

  /// Get the domain for a platform
  static String? getPrimaryDomain(String platform) {
    return _platformDomains[platform.toLowerCase()];
  }

  /// Check if a platform is supported
  static bool isPlatformSupported(String platform) {
    return _platformDomains.containsKey(platform.toLowerCase());
  }
}
