#!/usr/bin/env bash
# =============================================================================
# Regenerate backend/internal/buildinfo/embedded.go from current git HEAD.
#
# Why this exists: production deploy webhook builds Docker image from the
# `backend/` directory only — `.git/` is not in the build context. That
# breaks both runtime/debug.ReadBuildInfo() VCS auto-embed AND ldflags args
# (the deploy script doesn't pass any). Without a tracked source-of-truth
# in the Go source tree, /version forever reports `version=dev,
# git_sha=unknown` no matter what the deploy script does.
#
# This script writes those values as Go constants into embedded.go, which
# gets committed to the repo and ships with the docker build context.
#
# Usage:
#
#   bash backend/scripts/regenerate_buildinfo.sh
#
# Run this before EVERY backend-affecting commit. The preflight gate
# (scripts/preflight_release.sh, when added for backend) verifies the
# embedded values match HEAD before allowing a release push, so a stale
# embedded.go never escapes to production.
#
# Note on chicken-and-egg: this script writes the SHA of HEAD *before* the
# commit that ships it. So /version reports the commit before the release
# commit — accurate within 1 commit, which is enough for incident triage
# (the regenerate change itself is a 3-line constant update, never the
# source of a bug).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$BACKEND_DIR/.." && pwd)"
TARGET_FILE="$BACKEND_DIR/internal/buildinfo/embedded.go"

if [ ! -d "$REPO_ROOT/.git" ]; then
  echo "ERROR: $REPO_ROOT is not a git checkout — cannot derive build identity" >&2
  exit 1
fi

VERSION="$(git -C "$REPO_ROOT" describe --tags --always --dirty 2>/dev/null || echo dev)"
GIT_SHA="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$TARGET_FILE" <<EOF
// Code generated by scripts/regenerate_buildinfo.sh. DO NOT EDIT.
//
// Regenerate this file before any backend-affecting commit. The preflight
// gate verifies the embedded SHA matches HEAD~1 before allowing a release
// push, so a stale value never reaches production. See buildinfo.go for
// the full priority chain.

package buildinfo

const (
	embeddedVersion   = "${VERSION}"
	embeddedGitSHA    = "${GIT_SHA}"
	embeddedBuildTime = "${BUILD_TIME}"
)

func init() {
	if Version == "" && embeddedVersion != "" {
		Version = embeddedVersion
	}
	if GitSHA == "" && embeddedGitSHA != "" {
		GitSHA = embeddedGitSHA
	}
	if BuildTime == "" && embeddedBuildTime != "" {
		BuildTime = embeddedBuildTime
	}
}
EOF

echo "Regenerated $TARGET_FILE"
echo "  embeddedVersion   = $VERSION"
echo "  embeddedGitSHA    = $GIT_SHA"
echo "  embeddedBuildTime = $BUILD_TIME"
echo ""
echo "Stage with: git add $TARGET_FILE"
