// Code generated by scripts/regenerate_buildinfo.sh. DO NOT EDIT.
//
// Regenerate this file before any backend-affecting commit. The preflight
// gate verifies the embedded SHA matches HEAD~1 before allowing a release
// push, so a stale value never reaches production. See buildinfo.go for
// the full priority chain.

package buildinfo

const (
	embeddedVersion   = "v1.1.1-408-g7cd6900d"
	embeddedGitSHA    = "7cd6900dfa22994b325bbce7cfccb6a760083ddb"
	embeddedBuildTime = "2026-05-25T10:05:20Z"
)

func init() {
	if Version == "" && embeddedVersion != "" {
		Version = embeddedVersion
	}
	if GitSHA == "" && embeddedGitSHA != "" {
		GitSHA = embeddedGitSHA
	}
	if BuildTime == "" && embeddedBuildTime != "" {
		BuildTime = embeddedBuildTime
	}
}
