import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:svid/features/downloads/domain/entities/video_info.dart';
import 'package:svid/features/downloads/presentation/utils/download_format_warning.dart';
import 'package:svid/features/settings/domain/enums/audio_codec_preference.dart';
import 'package:svid/features/settings/domain/enums/container_format_preference.dart';
import 'package:svid/features/settings/domain/enums/download_engine.dart';
import 'package:svid/features/settings/domain/enums/fps_preference.dart';
import 'package:svid/features/settings/domain/enums/quality_preference.dart';
import 'package:svid/features/settings/domain/enums/video_codec_preference.dart';
import 'package:svid/features/settings/presentation/providers/settings_provider.dart';

void main() {
  group('downloadFormatWarning', () {
    test('does not warn for concrete Best 1080p MP4 quality', () {
      final warning = downloadFormatWarning(
        quality: _videoQuality('Best (1080p)'),
        config: null,
        settings: _settingsState(),
      );

      expect(warning, isNull);
    });

    // pick X → get X contract v2: format_selector no longer emits
    // `containerChanged` warnings. The recode notice for codec-mismatch
    // (e.g. MP4 at 4K) is generated by ContainerPlanner downstream and
    // shown as a pre-commit notice in the dialog, not via this helper.
    test('no longer warns for unbounded Best MP4 (planner emits notice)', () {
      final warning = downloadFormatWarning(
        quality: _videoQuality('Best'),
        config: null,
        settings: _settingsState(),
      );
      expect(warning, isNull,
          reason: 'Selector no longer swaps MP4→MKV; planner notice replaces');
    });

    test('no longer warns for concrete Best 2160p MP4', () {
      final warning = downloadFormatWarning(
        quality: _videoQuality('Best (2160p)'),
        config: null,
        settings: _settingsState(),
      );
      expect(warning, isNull,
          reason: 'pick X → get X: file IS .mp4 (recoded), no swap warning');
    });
  });
}

Quality _videoQuality(String qualityText) {
  return Quality(
    qualityText: qualityText,
    size: 'Unknown',
    encryptedUrl: 'ytdlp:best:mp4',
    mediaType: MediaType.video,
  );
}

SettingsState _settingsState() {
  return const SettingsState(
    downloadPath: '/tmp',
    maxConcurrentDownloads: 3,
    themeMode: ThemeMode.system,
    autoStartDownloads: false,
    autoClipboardDetection: true,
    notificationsEnabled: true,
    preferredQuality: QualityPreference.auto,
    downloadEngine: DownloadEngine.ytdlpOnly,
    enableApiFallback: false,
    autoUpdateYtdlp: true,
    ytdlpTimeout: 30,
    showDownloadMethodBadge: true,
    videoCodecPreference: VideoCodecPreference.h264,
    audioCodecPreference: AudioCodecPreference.aac,
    containerFormatPreference: ContainerFormatPreference.mp4,
    fpsPreference: FpsPreference.auto,
    maxResolution: 0,
    subtitlesEnabled: false,
    subtitlesLanguages: ['en'],
    subtitlesFormat: 'srt',
    embedSubtitles: true,
    writeThumbnail: false,
    embedThumbnail: true,
    embedMetadata: true,
    embedChapters: true,
    sponsorBlockEnabled: false,
    sponsorBlockAction: 'skip',
    sponsorBlockCategories: ['sponsor'],
    forceRemux: false,
    tiktokRemoveWatermark: true,
    geoBypass: false,
    archiveEnabled: false,
  );
}
