// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Get system information (test function)
Future<String> getSystemInfo() => RustLib.instance.api.crateApiGetSystemInfo();

/// Initialize Rust-side Sentry telemetry. FRB-visible wrapper around
/// [`crate::telemetry::init_telemetry`].
///
/// `rust_input: "crate::api"` in flutter_rust_bridge.yaml means FRB only
/// generates Dart bindings for `pub fn`s declared in this module. The
/// telemetry module's `init_telemetry` therefore needs a wrapper here so
/// `native.initTelemetry(...)` is callable from Dart.
///
/// # Args
/// - `dsn`: Sentry DSN. Empty string disables Sentry; the on-disk panic
///   fallback still runs.
/// - `release`: e.g. `"ssvid@1.3.7+12"` — passed from Dart so the release
///   tag tracks `AppConstants.appVersion` + brand, NOT the Rust crate's
///   `0.1.0` `CARGO_PKG_VERSION`.
/// - `panic_dir`: brand-resolved absolute path for panic JSON files.
Future<void> initTelemetry({String? dsn, required String release, required String panicDir}) =>
    RustLib.instance.api.crateApiInitTelemetry(dsn: dsn, release: release, panicDir: panicDir);

/// Download a file from URL to path
Future<String> downloadFile({required String url, required String path}) =>
    RustLib.instance.api.crateApiDownloadFile(url: url, path: path);

/// Get directory size recursively
Future<BigInt> getDirectorySize({required String path}) => RustLib.instance.api.crateApiGetDirectorySize(path: path);

/// Check if yt-dlp is available
Future<bool> ytdlpIsAvailable({required String binaryPath}) =>
    RustLib.instance.api.crateApiYtdlpIsAvailable(binaryPath: binaryPath);

/// Get yt-dlp version
Future<String> ytdlpGetVersion({required String binaryPath}) =>
    RustLib.instance.api.crateApiYtdlpGetVersion(binaryPath: binaryPath);

/// Extract video information without downloading
Future<YtDlpVideoInfoDto> ytdlpExtractInfo({
  required String binaryPath,
  required String url,
  String? cookiesFile,
  String? cookiesFromBrowser,
  String? proxyUrl,
  String? extractorClient,
  BigInt? timeoutSecs,
  String? jsRuntimePath,
}) => RustLib.instance.api.crateApiYtdlpExtractInfo(
  binaryPath: binaryPath,
  url: url,
  cookiesFile: cookiesFile,
  cookiesFromBrowser: cookiesFromBrowser,
  proxyUrl: proxyUrl,
  extractorClient: extractorClient,
  timeoutSecs: timeoutSecs,
  jsRuntimePath: jsRuntimePath,
);

/// Search YouTube videos
/// Returns a list of search results with basic metadata
///
/// # Arguments
/// * `binary_path` - Path to yt-dlp binary
/// * `query` - Search query string
/// * `max_results` - Maximum number of results (1-50, default: 20)
/// * `cookies_file` - Optional cookies file for age-restricted content
Future<List<YouTubeSearchResultDto>> ytdlpSearchYoutube({
  required String binaryPath,
  required String query,
  required int maxResults,
  String? cookiesFile,
  String? cookiesFromBrowser,
  String? jsRuntimePath,
}) => RustLib.instance.api.crateApiYtdlpSearchYoutube(
  binaryPath: binaryPath,
  query: query,
  maxResults: maxResults,
  cookiesFile: cookiesFile,
  cookiesFromBrowser: cookiesFromBrowser,
  jsRuntimePath: jsRuntimePath,
);

/// Get YouTube playlist information with pagination support
/// Returns playlist metadata and list of videos for the specified range
///
/// # Arguments
/// * `binary_path` - Path to yt-dlp binary
/// * `url` - Playlist URL (e.g., https://www.youtube.com/playlist?list=...)
/// * `start_index` - Start index (1-based, 0 = from beginning)
/// * `end_index` - End index (1-based, 0 = no limit)
/// * `cookies_file` - Optional cookies file for private/age-restricted playlists
Future<(PlaylistInfoDto, List<PlaylistVideoDto>)> ytdlpGetPlaylistInfo({
  required String binaryPath,
  required String url,
  required int startIndex,
  required int endIndex,
  String? cookiesFile,
  String? cookiesFromBrowser,
  String? jsRuntimePath,
}) => RustLib.instance.api.crateApiYtdlpGetPlaylistInfo(
  binaryPath: binaryPath,
  url: url,
  startIndex: startIndex,
  endIndex: endIndex,
  cookiesFile: cookiesFile,
  cookiesFromBrowser: cookiesFromBrowser,
  jsRuntimePath: jsRuntimePath,
);

/// Get YouTube channel information with pagination support
/// Returns channel metadata and list of videos for the specified range
/// Works with @username, /c/channel, /channel/ID URLs
///
/// # Arguments
/// * `binary_path` - Path to yt-dlp binary
/// * `url` - Channel URL (e.g., https://www.youtube.com/@username or /channel/UCID)
/// * `start_index` - Start index (1-based, 0 = from beginning)
/// * `end_index` - End index (1-based, 0 = no limit)
/// * `cookies_file` - Optional cookies file for age-restricted channels
Future<(ChannelInfoDto, List<PlaylistVideoDto>)> ytdlpGetChannelInfo({
  required String binaryPath,
  required String url,
  required int startIndex,
  required int endIndex,
  String? cookiesFile,
  String? cookiesFromBrowser,
  String? jsRuntimePath,
}) => RustLib.instance.api.crateApiYtdlpGetChannelInfo(
  binaryPath: binaryPath,
  url: url,
  startIndex: startIndex,
  endIndex: endIndex,
  cookiesFile: cookiesFile,
  cookiesFromBrowser: cookiesFromBrowser,
  jsRuntimePath: jsRuntimePath,
);

/// Get YouTube channel metadata ONLY (accurate avatar, banner, description)
/// This is a separate call optimized for getting channel page data without videos
/// Use this when you need accurate channel thumbnails/avatars for subscriptions
///
/// # Arguments
/// * `binary_path` - Path to yt-dlp binary
/// * `url` - Channel URL (e.g., https://www.youtube.com/@username or /channel/UCID)
/// * `cookies_file` - Optional cookies file for age-restricted channels
Future<ChannelInfoDto> ytdlpGetChannelMetadata({
  required String binaryPath,
  required String url,
  String? cookiesFile,
  String? cookiesFromBrowser,
  String? jsRuntimePath,
}) => RustLib.instance.api.crateApiYtdlpGetChannelMetadata(
  binaryPath: binaryPath,
  url: url,
  cookiesFile: cookiesFile,
  cookiesFromBrowser: cookiesFromBrowser,
  jsRuntimePath: jsRuntimePath,
);

/// Parse yt-dlp progress line (helper for Dart-side parsing)
Future<YtDlpProgressDto?> ytdlpParseProgress({required String line}) =>
    RustLib.instance.api.crateApiYtdlpParseProgress(line: line);

/// Initialize download manager (call once at app start)
Future<void> downloadManagerInit({required int maxConcurrent}) =>
    RustLib.instance.api.crateApiDownloadManagerInit(maxConcurrent: maxConcurrent);

/// Start a new download with optional resume offset, speed limit, segment count, user agent, and proxy
///
/// # Arguments
/// * `id` - UUID string for download tracking
/// * `url` - Direct HTTP URL to download from
/// * `output_path` - File path to save download
/// * `resume_offset` - Optional byte offset to resume from (0 = start new download)
/// * `max_speed_bytes` - Optional speed limit in bytes/second (0 or None = unlimited)
/// * `num_segments` - Optional number of parallel segments (None/1 = single-stream, 2-16 = segmented)
/// * `user_agent` - Optional User-Agent string for HTTP requests (None = default Chrome UA)
/// * `proxy_url` - Optional proxy URL (e.g. "http://host:port", "socks5://host:port"; None = no proxy)
Future<void> downloadStart({
  required String id,
  required String url,
  required String outputPath,
  BigInt? resumeOffset,
  BigInt? maxSpeedBytes,
  int? numSegments,
  String? userAgent,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiDownloadStart(
  id: id,
  url: url,
  outputPath: outputPath,
  resumeOffset: resumeOffset,
  maxSpeedBytes: maxSpeedBytes,
  numSegments: numSegments,
  userAgent: userAgent,
  proxyUrl: proxyUrl,
);

/// Start a download with custom HTTP headers and cookies (IDM mode).
///
/// This is the advanced API used by the browser media interceptor to download
/// URLs directly with the browser's authentication context.
///
/// # Arguments
/// * `id` - UUID string for download tracking
/// * `url` - Direct HTTP URL to download from
/// * `output_path` - File path to save download
/// * `resume_offset` - Optional byte offset to resume from
/// * `max_speed_bytes` - Optional speed limit in bytes/second
/// * `num_segments` - Optional number of parallel segments (1 = single-stream, 2-16 = segmented)
/// * `user_agent` - Optional User-Agent string
/// * `proxy_url` - Optional proxy URL
/// * `headers_json` - Optional JSON string of custom HTTP headers: `{"Cookie":"…","Referer":"…"}`
/// * `cookies_string` - Optional raw cookie string: `"key1=val1; key2=val2"`
Future<void> downloadStartWithHeaders({
  required String id,
  required String url,
  required String outputPath,
  BigInt? resumeOffset,
  BigInt? maxSpeedBytes,
  int? numSegments,
  String? userAgent,
  String? proxyUrl,
  String? headersJson,
  String? cookiesString,
}) => RustLib.instance.api.crateApiDownloadStartWithHeaders(
  id: id,
  url: url,
  outputPath: outputPath,
  resumeOffset: resumeOffset,
  maxSpeedBytes: maxSpeedBytes,
  numSegments: numSegments,
  userAgent: userAgent,
  proxyUrl: proxyUrl,
  headersJson: headersJson,
  cookiesString: cookiesString,
);

/// Pause a download
Future<void> downloadPause({required String id}) => RustLib.instance.api.crateApiDownloadPause(id: id);

/// Resume a download
Future<void> downloadResume({required String id}) => RustLib.instance.api.crateApiDownloadResume(id: id);

/// Cancel a download
Future<void> downloadCancel({required String id}) => RustLib.instance.api.crateApiDownloadCancel(id: id);

/// Get download progress
Future<DownloadProgressDto> downloadGetProgress({required String id}) =>
    RustLib.instance.api.crateApiDownloadGetProgress(id: id);

/// Remove a completed/failed/cancelled download from Rust memory.
/// Call this after a download reaches a terminal state to prevent memory leaks.
Future<void> downloadCleanup({required String id}) => RustLib.instance.api.crateApiDownloadCleanup(id: id);

/// Channel info DTO
class ChannelInfoDto {
  final String id;
  final String title;
  final String? uploader;
  final String? uploaderId;
  final String? thumbnail;
  final String? description;
  final BigInt? subscriberCount;
  final int? videoCount;
  final String webpageUrl;

  const ChannelInfoDto({
    required this.id,
    required this.title,
    this.uploader,
    this.uploaderId,
    this.thumbnail,
    this.description,
    this.subscriberCount,
    this.videoCount,
    required this.webpageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      uploader.hashCode ^
      uploaderId.hashCode ^
      thumbnail.hashCode ^
      description.hashCode ^
      subscriberCount.hashCode ^
      videoCount.hashCode ^
      webpageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          uploader == other.uploader &&
          uploaderId == other.uploaderId &&
          thumbnail == other.thumbnail &&
          description == other.description &&
          subscriberCount == other.subscriberCount &&
          videoCount == other.videoCount &&
          webpageUrl == other.webpageUrl;
}

/// Chapter information
class ChapterInfoDto {
  final String title;
  final double startTime;
  final double endTime;

  const ChapterInfoDto({required this.title, required this.startTime, required this.endTime});

  @override
  int get hashCode => title.hashCode ^ startTime.hashCode ^ endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterInfoDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          startTime == other.startTime &&
          endTime == other.endTime;
}

/// Download progress DTO
class DownloadProgressDto {
  final String id;
  final BigInt downloadedBytes;
  final BigInt totalBytes;
  final String status;

  const DownloadProgressDto({
    required this.id,
    required this.downloadedBytes,
    required this.totalBytes,
    required this.status,
  });

  @override
  int get hashCode => id.hashCode ^ downloadedBytes.hashCode ^ totalBytes.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgressDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          downloadedBytes == other.downloadedBytes &&
          totalBytes == other.totalBytes &&
          status == other.status;
}

/// Playlist info DTO
class PlaylistInfoDto {
  final String id;
  final String title;
  final String? uploader;
  final String? uploaderId;
  final String? thumbnail;
  final String? description;
  final int? videoCount;
  final String webpageUrl;

  const PlaylistInfoDto({
    required this.id,
    required this.title,
    this.uploader,
    this.uploaderId,
    this.thumbnail,
    this.description,
    this.videoCount,
    required this.webpageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      uploader.hashCode ^
      uploaderId.hashCode ^
      thumbnail.hashCode ^
      description.hashCode ^
      videoCount.hashCode ^
      webpageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          uploader == other.uploader &&
          uploaderId == other.uploaderId &&
          thumbnail == other.thumbnail &&
          description == other.description &&
          videoCount == other.videoCount &&
          webpageUrl == other.webpageUrl;
}

/// Playlist video DTO
class PlaylistVideoDto {
  final String id;
  final String title;
  final String url;
  final String? thumbnail;
  final BigInt? duration;
  final String? channel;
  final String? channelId;
  final BigInt? viewCount;
  final String? uploadDate;

  const PlaylistVideoDto({
    required this.id,
    required this.title,
    required this.url,
    this.thumbnail,
    this.duration,
    this.channel,
    this.channelId,
    this.viewCount,
    this.uploadDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      url.hashCode ^
      thumbnail.hashCode ^
      duration.hashCode ^
      channel.hashCode ^
      channelId.hashCode ^
      viewCount.hashCode ^
      uploadDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistVideoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          url == other.url &&
          thumbnail == other.thumbnail &&
          duration == other.duration &&
          channel == other.channel &&
          channelId == other.channelId &&
          viewCount == other.viewCount &&
          uploadDate == other.uploadDate;
}

/// Subtitle track information
class SubtitleInfoDto {
  final String lang;
  final String? langName;
  final String ext;
  final String? url;

  const SubtitleInfoDto({required this.lang, this.langName, required this.ext, this.url});

  @override
  int get hashCode => lang.hashCode ^ langName.hashCode ^ ext.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleInfoDto &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          langName == other.langName &&
          ext == other.ext &&
          url == other.url;
}

/// YouTube search result DTO
class YouTubeSearchResultDto {
  final String id;
  final String title;
  final String? channel;
  final String? channelId;
  final String? thumbnail;
  final BigInt? duration;
  final BigInt? viewCount;
  final String? uploadDate;
  final String url;
  final String? description;

  const YouTubeSearchResultDto({
    required this.id,
    required this.title,
    this.channel,
    this.channelId,
    this.thumbnail,
    this.duration,
    this.viewCount,
    this.uploadDate,
    required this.url,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      channel.hashCode ^
      channelId.hashCode ^
      thumbnail.hashCode ^
      duration.hashCode ^
      viewCount.hashCode ^
      uploadDate.hashCode ^
      url.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YouTubeSearchResultDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          channel == other.channel &&
          channelId == other.channelId &&
          thumbnail == other.thumbnail &&
          duration == other.duration &&
          viewCount == other.viewCount &&
          uploadDate == other.uploadDate &&
          url == other.url &&
          description == other.description;
}

/// Format/quality option from yt-dlp
class YtDlpFormatDto {
  final String formatId;
  final String ext;
  final String? resolution;
  final int? height;
  final int? width;
  final BigInt? filesize;
  final String? vcodec;
  final String? acodec;
  final double? fps;
  final double? tbr;
  final String? formatNote;

  const YtDlpFormatDto({
    required this.formatId,
    required this.ext,
    this.resolution,
    this.height,
    this.width,
    this.filesize,
    this.vcodec,
    this.acodec,
    this.fps,
    this.tbr,
    this.formatNote,
  });

  @override
  int get hashCode =>
      formatId.hashCode ^
      ext.hashCode ^
      resolution.hashCode ^
      height.hashCode ^
      width.hashCode ^
      filesize.hashCode ^
      vcodec.hashCode ^
      acodec.hashCode ^
      fps.hashCode ^
      tbr.hashCode ^
      formatNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YtDlpFormatDto &&
          runtimeType == other.runtimeType &&
          formatId == other.formatId &&
          ext == other.ext &&
          resolution == other.resolution &&
          height == other.height &&
          width == other.width &&
          filesize == other.filesize &&
          vcodec == other.vcodec &&
          acodec == other.acodec &&
          fps == other.fps &&
          tbr == other.tbr &&
          formatNote == other.formatNote;
}

/// Progress DTO for Dart
class YtDlpProgressDto {
  final double percent;
  final BigInt? downloadedBytes;
  final BigInt? totalBytes;
  final double? speed;
  final BigInt? etaSeconds;
  final String status;

  const YtDlpProgressDto({
    required this.percent,
    this.downloadedBytes,
    this.totalBytes,
    this.speed,
    this.etaSeconds,
    required this.status,
  });

  @override
  int get hashCode =>
      percent.hashCode ^
      downloadedBytes.hashCode ^
      totalBytes.hashCode ^
      speed.hashCode ^
      etaSeconds.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YtDlpProgressDto &&
          runtimeType == other.runtimeType &&
          percent == other.percent &&
          downloadedBytes == other.downloadedBytes &&
          totalBytes == other.totalBytes &&
          speed == other.speed &&
          etaSeconds == other.etaSeconds &&
          status == other.status;
}

/// Video information from yt-dlp
class YtDlpVideoInfoDto {
  final String id;
  final String title;
  final String? description;
  final String? uploader;
  final String? uploaderId;
  final BigInt? duration;
  final BigInt? viewCount;
  final BigInt? likeCount;
  final String? uploadDate;
  final String? thumbnail;
  final String? webpageUrl;
  final String? extractor;
  final List<YtDlpFormatDto> formats;
  final List<SubtitleInfoDto> subtitles;
  final List<SubtitleInfoDto> automaticCaptions;
  final List<ChapterInfoDto> chapters;
  final bool isLive;
  final String? liveStatus;

  const YtDlpVideoInfoDto({
    required this.id,
    required this.title,
    this.description,
    this.uploader,
    this.uploaderId,
    this.duration,
    this.viewCount,
    this.likeCount,
    this.uploadDate,
    this.thumbnail,
    this.webpageUrl,
    this.extractor,
    required this.formats,
    required this.subtitles,
    required this.automaticCaptions,
    required this.chapters,
    required this.isLive,
    this.liveStatus,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      description.hashCode ^
      uploader.hashCode ^
      uploaderId.hashCode ^
      duration.hashCode ^
      viewCount.hashCode ^
      likeCount.hashCode ^
      uploadDate.hashCode ^
      thumbnail.hashCode ^
      webpageUrl.hashCode ^
      extractor.hashCode ^
      formats.hashCode ^
      subtitles.hashCode ^
      automaticCaptions.hashCode ^
      chapters.hashCode ^
      isLive.hashCode ^
      liveStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YtDlpVideoInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          uploader == other.uploader &&
          uploaderId == other.uploaderId &&
          duration == other.duration &&
          viewCount == other.viewCount &&
          likeCount == other.likeCount &&
          uploadDate == other.uploadDate &&
          thumbnail == other.thumbnail &&
          webpageUrl == other.webpageUrl &&
          extractor == other.extractor &&
          formats == other.formats &&
          subtitles == other.subtitles &&
          automaticCaptions == other.automaticCaptions &&
          chapters == other.chapters &&
          isLive == other.isLive &&
          liveStatus == other.liveStatus;
}
