// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  YtDlpProgressDto dco_decode_box_autoadd_yt_dlp_progress_dto(dynamic raw);

  @protected
  ChannelInfoDto dco_decode_channel_info_dto(dynamic raw);

  @protected
  ChapterInfoDto dco_decode_chapter_info_dto(dynamic raw);

  @protected
  DownloadProgressDto dco_decode_download_progress_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<ChapterInfoDto> dco_decode_list_chapter_info_dto(dynamic raw);

  @protected
  List<PlaylistVideoDto> dco_decode_list_playlist_video_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SubtitleInfoDto> dco_decode_list_subtitle_info_dto(dynamic raw);

  @protected
  List<YouTubeSearchResultDto> dco_decode_list_you_tube_search_result_dto(dynamic raw);

  @protected
  List<YtDlpFormatDto> dco_decode_list_yt_dlp_format_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  YtDlpProgressDto? dco_decode_opt_box_autoadd_yt_dlp_progress_dto(dynamic raw);

  @protected
  PlaylistInfoDto dco_decode_playlist_info_dto(dynamic raw);

  @protected
  PlaylistVideoDto dco_decode_playlist_video_dto(dynamic raw);

  @protected
  (ChannelInfoDto, List<PlaylistVideoDto>) dco_decode_record_channel_info_dto_list_playlist_video_dto(dynamic raw);

  @protected
  (PlaylistInfoDto, List<PlaylistVideoDto>) dco_decode_record_playlist_info_dto_list_playlist_video_dto(dynamic raw);

  @protected
  SubtitleInfoDto dco_decode_subtitle_info_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  YouTubeSearchResultDto dco_decode_you_tube_search_result_dto(dynamic raw);

  @protected
  YtDlpFormatDto dco_decode_yt_dlp_format_dto(dynamic raw);

  @protected
  YtDlpProgressDto dco_decode_yt_dlp_progress_dto(dynamic raw);

  @protected
  YtDlpVideoInfoDto dco_decode_yt_dlp_video_info_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  YtDlpProgressDto sse_decode_box_autoadd_yt_dlp_progress_dto(SseDeserializer deserializer);

  @protected
  ChannelInfoDto sse_decode_channel_info_dto(SseDeserializer deserializer);

  @protected
  ChapterInfoDto sse_decode_chapter_info_dto(SseDeserializer deserializer);

  @protected
  DownloadProgressDto sse_decode_download_progress_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<ChapterInfoDto> sse_decode_list_chapter_info_dto(SseDeserializer deserializer);

  @protected
  List<PlaylistVideoDto> sse_decode_list_playlist_video_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SubtitleInfoDto> sse_decode_list_subtitle_info_dto(SseDeserializer deserializer);

  @protected
  List<YouTubeSearchResultDto> sse_decode_list_you_tube_search_result_dto(SseDeserializer deserializer);

  @protected
  List<YtDlpFormatDto> sse_decode_list_yt_dlp_format_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  YtDlpProgressDto? sse_decode_opt_box_autoadd_yt_dlp_progress_dto(SseDeserializer deserializer);

  @protected
  PlaylistInfoDto sse_decode_playlist_info_dto(SseDeserializer deserializer);

  @protected
  PlaylistVideoDto sse_decode_playlist_video_dto(SseDeserializer deserializer);

  @protected
  (ChannelInfoDto, List<PlaylistVideoDto>) sse_decode_record_channel_info_dto_list_playlist_video_dto(
    SseDeserializer deserializer,
  );

  @protected
  (PlaylistInfoDto, List<PlaylistVideoDto>) sse_decode_record_playlist_info_dto_list_playlist_video_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubtitleInfoDto sse_decode_subtitle_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  YouTubeSearchResultDto sse_decode_you_tube_search_result_dto(SseDeserializer deserializer);

  @protected
  YtDlpFormatDto sse_decode_yt_dlp_format_dto(SseDeserializer deserializer);

  @protected
  YtDlpProgressDto sse_decode_yt_dlp_progress_dto(SseDeserializer deserializer);

  @protected
  YtDlpVideoInfoDto sse_decode_yt_dlp_video_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_yt_dlp_progress_dto(YtDlpProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_channel_info_dto(ChannelInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_info_dto(ChapterInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress_dto(DownloadProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_info_dto(List<ChapterInfoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_playlist_video_dto(List<PlaylistVideoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_subtitle_info_dto(List<SubtitleInfoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_you_tube_search_result_dto(List<YouTubeSearchResultDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_yt_dlp_format_dto(List<YtDlpFormatDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_yt_dlp_progress_dto(YtDlpProgressDto? self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_info_dto(PlaylistInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_video_dto(PlaylistVideoDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_channel_info_dto_list_playlist_video_dto(
    (ChannelInfoDto, List<PlaylistVideoDto>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_playlist_info_dto_list_playlist_video_dto(
    (PlaylistInfoDto, List<PlaylistVideoDto>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtitle_info_dto(SubtitleInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_you_tube_search_result_dto(YouTubeSearchResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_yt_dlp_format_dto(YtDlpFormatDto self, SseSerializer serializer);

  @protected
  void sse_encode_yt_dlp_progress_dto(YtDlpProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_yt_dlp_video_info_dto(YtDlpVideoInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
