// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -912926833;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'native',
    ioDirectory: 'native/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiDownloadCancel({required String id});

  Future<void> crateApiDownloadCleanup({required String id});

  Future<String> crateApiDownloadFile({required String url, required String path});

  Future<DownloadProgressDto> crateApiDownloadGetProgress({required String id});

  Future<void> crateApiDownloadManagerInit({required int maxConcurrent});

  Future<void> crateApiDownloadPause({required String id});

  Future<void> crateApiDownloadResume({required String id});

  Future<void> crateApiDownloadStart({
    required String id,
    required String url,
    required String outputPath,
    BigInt? resumeOffset,
    BigInt? maxSpeedBytes,
    int? numSegments,
    String? userAgent,
    String? proxyUrl,
  });

  Future<void> crateApiDownloadStartWithHeaders({
    required String id,
    required String url,
    required String outputPath,
    BigInt? resumeOffset,
    BigInt? maxSpeedBytes,
    int? numSegments,
    String? userAgent,
    String? proxyUrl,
    String? headersJson,
    String? cookiesString,
  });

  Future<BigInt> crateApiGetDirectorySize({required String path});

  Future<String> crateApiGetSystemInfo();

  Future<void> crateApiInitTelemetry({String? dsn, required String release, required String panicDir});

  Future<YtDlpVideoInfoDto> crateApiYtdlpExtractInfo({
    required String binaryPath,
    required String url,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? proxyUrl,
    String? extractorClient,
    BigInt? timeoutSecs,
    String? jsRuntimePath,
  });

  Future<(ChannelInfoDto, List<PlaylistVideoDto>)> crateApiYtdlpGetChannelInfo({
    required String binaryPath,
    required String url,
    required int startIndex,
    required int endIndex,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  });

  Future<ChannelInfoDto> crateApiYtdlpGetChannelMetadata({
    required String binaryPath,
    required String url,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  });

  Future<(PlaylistInfoDto, List<PlaylistVideoDto>)> crateApiYtdlpGetPlaylistInfo({
    required String binaryPath,
    required String url,
    required int startIndex,
    required int endIndex,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  });

  Future<String> crateApiYtdlpGetVersion({required String binaryPath});

  Future<bool> crateApiYtdlpIsAvailable({required String binaryPath});

  Future<YtDlpProgressDto?> crateApiYtdlpParseProgress({required String line});

  Future<List<YouTubeSearchResultDto>> crateApiYtdlpSearchYoutube({
    required String binaryPath,
    required String query,
    required int maxResults,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDownloadCancel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadCancelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadCancelConstMeta =>
      const TaskConstMeta(debugName: "download_cancel", argNames: ["id"]);

  @override
  Future<void> crateApiDownloadCleanup({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadCleanupConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadCleanupConstMeta =>
      const TaskConstMeta(debugName: "download_cleanup", argNames: ["id"]);

  @override
  Future<String> crateApiDownloadFile({required String url, required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadFileConstMeta,
        argValues: [url, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadFileConstMeta =>
      const TaskConstMeta(debugName: "download_file", argNames: ["url", "path"]);

  @override
  Future<DownloadProgressDto> crateApiDownloadGetProgress({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_progress_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDownloadGetProgressConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadGetProgressConstMeta =>
      const TaskConstMeta(debugName: "download_get_progress", argNames: ["id"]);

  @override
  Future<void> crateApiDownloadManagerInit({required int maxConcurrent}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(maxConcurrent, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadManagerInitConstMeta,
        argValues: [maxConcurrent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadManagerInitConstMeta =>
      const TaskConstMeta(debugName: "download_manager_init", argNames: ["maxConcurrent"]);

  @override
  Future<void> crateApiDownloadPause({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadPauseConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadPauseConstMeta =>
      const TaskConstMeta(debugName: "download_pause", argNames: ["id"]);

  @override
  Future<void> crateApiDownloadResume({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadResumeConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadResumeConstMeta =>
      const TaskConstMeta(debugName: "download_resume", argNames: ["id"]);

  @override
  Future<void> crateApiDownloadStart({
    required String id,
    required String url,
    required String outputPath,
    BigInt? resumeOffset,
    BigInt? maxSpeedBytes,
    int? numSegments,
    String? userAgent,
    String? proxyUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(url, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_opt_box_autoadd_u_64(resumeOffset, serializer);
          sse_encode_opt_box_autoadd_u_64(maxSpeedBytes, serializer);
          sse_encode_opt_box_autoadd_u_32(numSegments, serializer);
          sse_encode_opt_String(userAgent, serializer);
          sse_encode_opt_String(proxyUrl, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadStartConstMeta,
        argValues: [id, url, outputPath, resumeOffset, maxSpeedBytes, numSegments, userAgent, proxyUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadStartConstMeta => const TaskConstMeta(
    debugName: "download_start",
    argNames: ["id", "url", "outputPath", "resumeOffset", "maxSpeedBytes", "numSegments", "userAgent", "proxyUrl"],
  );

  @override
  Future<void> crateApiDownloadStartWithHeaders({
    required String id,
    required String url,
    required String outputPath,
    BigInt? resumeOffset,
    BigInt? maxSpeedBytes,
    int? numSegments,
    String? userAgent,
    String? proxyUrl,
    String? headersJson,
    String? cookiesString,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(url, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_opt_box_autoadd_u_64(resumeOffset, serializer);
          sse_encode_opt_box_autoadd_u_64(maxSpeedBytes, serializer);
          sse_encode_opt_box_autoadd_u_32(numSegments, serializer);
          sse_encode_opt_String(userAgent, serializer);
          sse_encode_opt_String(proxyUrl, serializer);
          sse_encode_opt_String(headersJson, serializer);
          sse_encode_opt_String(cookiesString, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiDownloadStartWithHeadersConstMeta,
        argValues: [
          id,
          url,
          outputPath,
          resumeOffset,
          maxSpeedBytes,
          numSegments,
          userAgent,
          proxyUrl,
          headersJson,
          cookiesString,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadStartWithHeadersConstMeta => const TaskConstMeta(
    debugName: "download_start_with_headers",
    argNames: [
      "id",
      "url",
      "outputPath",
      "resumeOffset",
      "maxSpeedBytes",
      "numSegments",
      "userAgent",
      "proxyUrl",
      "headersJson",
      "cookiesString",
    ],
  );

  @override
  Future<BigInt> crateApiGetDirectorySize({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_64, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiGetDirectorySizeConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDirectorySizeConstMeta =>
      const TaskConstMeta(debugName: "get_directory_size", argNames: ["path"]);

  @override
  Future<String> crateApiGetSystemInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: null),
        constMeta: kCrateApiGetSystemInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSystemInfoConstMeta => const TaskConstMeta(debugName: "get_system_info", argNames: []);

  @override
  Future<void> crateApiInitTelemetry({String? dsn, required String release, required String panicDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(dsn, serializer);
          sse_encode_String(release, serializer);
          sse_encode_String(panicDir, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
        constMeta: kCrateApiInitTelemetryConstMeta,
        argValues: [dsn, release, panicDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitTelemetryConstMeta =>
      const TaskConstMeta(debugName: "init_telemetry", argNames: ["dsn", "release", "panicDir"]);

  @override
  Future<YtDlpVideoInfoDto> crateApiYtdlpExtractInfo({
    required String binaryPath,
    required String url,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? proxyUrl,
    String? extractorClient,
    BigInt? timeoutSecs,
    String? jsRuntimePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(cookiesFile, serializer);
          sse_encode_opt_String(cookiesFromBrowser, serializer);
          sse_encode_opt_String(proxyUrl, serializer);
          sse_encode_opt_String(extractorClient, serializer);
          sse_encode_opt_box_autoadd_u_64(timeoutSecs, serializer);
          sse_encode_opt_String(jsRuntimePath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_yt_dlp_video_info_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYtdlpExtractInfoConstMeta,
        argValues: [
          binaryPath,
          url,
          cookiesFile,
          cookiesFromBrowser,
          proxyUrl,
          extractorClient,
          timeoutSecs,
          jsRuntimePath,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpExtractInfoConstMeta => const TaskConstMeta(
    debugName: "ytdlp_extract_info",
    argNames: [
      "binaryPath",
      "url",
      "cookiesFile",
      "cookiesFromBrowser",
      "proxyUrl",
      "extractorClient",
      "timeoutSecs",
      "jsRuntimePath",
    ],
  );

  @override
  Future<(ChannelInfoDto, List<PlaylistVideoDto>)> crateApiYtdlpGetChannelInfo({
    required String binaryPath,
    required String url,
    required int startIndex,
    required int endIndex,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(url, serializer);
          sse_encode_u_32(startIndex, serializer);
          sse_encode_u_32(endIndex, serializer);
          sse_encode_opt_String(cookiesFile, serializer);
          sse_encode_opt_String(cookiesFromBrowser, serializer);
          sse_encode_opt_String(jsRuntimePath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_channel_info_dto_list_playlist_video_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYtdlpGetChannelInfoConstMeta,
        argValues: [binaryPath, url, startIndex, endIndex, cookiesFile, cookiesFromBrowser, jsRuntimePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpGetChannelInfoConstMeta => const TaskConstMeta(
    debugName: "ytdlp_get_channel_info",
    argNames: ["binaryPath", "url", "startIndex", "endIndex", "cookiesFile", "cookiesFromBrowser", "jsRuntimePath"],
  );

  @override
  Future<ChannelInfoDto> crateApiYtdlpGetChannelMetadata({
    required String binaryPath,
    required String url,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(cookiesFile, serializer);
          sse_encode_opt_String(cookiesFromBrowser, serializer);
          sse_encode_opt_String(jsRuntimePath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_channel_info_dto, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiYtdlpGetChannelMetadataConstMeta,
        argValues: [binaryPath, url, cookiesFile, cookiesFromBrowser, jsRuntimePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpGetChannelMetadataConstMeta => const TaskConstMeta(
    debugName: "ytdlp_get_channel_metadata",
    argNames: ["binaryPath", "url", "cookiesFile", "cookiesFromBrowser", "jsRuntimePath"],
  );

  @override
  Future<(PlaylistInfoDto, List<PlaylistVideoDto>)> crateApiYtdlpGetPlaylistInfo({
    required String binaryPath,
    required String url,
    required int startIndex,
    required int endIndex,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(url, serializer);
          sse_encode_u_32(startIndex, serializer);
          sse_encode_u_32(endIndex, serializer);
          sse_encode_opt_String(cookiesFile, serializer);
          sse_encode_opt_String(cookiesFromBrowser, serializer);
          sse_encode_opt_String(jsRuntimePath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_playlist_info_dto_list_playlist_video_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYtdlpGetPlaylistInfoConstMeta,
        argValues: [binaryPath, url, startIndex, endIndex, cookiesFile, cookiesFromBrowser, jsRuntimePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpGetPlaylistInfoConstMeta => const TaskConstMeta(
    debugName: "ytdlp_get_playlist_info",
    argNames: ["binaryPath", "url", "startIndex", "endIndex", "cookiesFile", "cookiesFromBrowser", "jsRuntimePath"],
  );

  @override
  Future<String> crateApiYtdlpGetVersion({required String binaryPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiYtdlpGetVersionConstMeta,
        argValues: [binaryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpGetVersionConstMeta =>
      const TaskConstMeta(debugName: "ytdlp_get_version", argNames: ["binaryPath"]);

  @override
  Future<bool> crateApiYtdlpIsAvailable({required String binaryPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_bool, decodeErrorData: null),
        constMeta: kCrateApiYtdlpIsAvailableConstMeta,
        argValues: [binaryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpIsAvailableConstMeta =>
      const TaskConstMeta(debugName: "ytdlp_is_available", argNames: ["binaryPath"]);

  @override
  Future<YtDlpProgressDto?> crateApiYtdlpParseProgress({required String line}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(line, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_opt_box_autoadd_yt_dlp_progress_dto, decodeErrorData: null),
        constMeta: kCrateApiYtdlpParseProgressConstMeta,
        argValues: [line],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpParseProgressConstMeta =>
      const TaskConstMeta(debugName: "ytdlp_parse_progress", argNames: ["line"]);

  @override
  Future<List<YouTubeSearchResultDto>> crateApiYtdlpSearchYoutube({
    required String binaryPath,
    required String query,
    required int maxResults,
    String? cookiesFile,
    String? cookiesFromBrowser,
    String? jsRuntimePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binaryPath, serializer);
          sse_encode_String(query, serializer);
          sse_encode_u_32(maxResults, serializer);
          sse_encode_opt_String(cookiesFile, serializer);
          sse_encode_opt_String(cookiesFromBrowser, serializer);
          sse_encode_opt_String(jsRuntimePath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_you_tube_search_result_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYtdlpSearchYoutubeConstMeta,
        argValues: [binaryPath, query, maxResults, cookiesFile, cookiesFromBrowser, jsRuntimePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYtdlpSearchYoutubeConstMeta => const TaskConstMeta(
    debugName: "ytdlp_search_youtube",
    argNames: ["binaryPath", "query", "maxResults", "cookiesFile", "cookiesFromBrowser", "jsRuntimePath"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  YtDlpProgressDto dco_decode_box_autoadd_yt_dlp_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_yt_dlp_progress_dto(raw);
  }

  @protected
  ChannelInfoDto dco_decode_channel_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ChannelInfoDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      uploader: dco_decode_opt_String(arr[2]),
      uploaderId: dco_decode_opt_String(arr[3]),
      thumbnail: dco_decode_opt_String(arr[4]),
      description: dco_decode_opt_String(arr[5]),
      subscriberCount: dco_decode_opt_box_autoadd_u_64(arr[6]),
      videoCount: dco_decode_opt_box_autoadd_u_32(arr[7]),
      webpageUrl: dco_decode_String(arr[8]),
    );
  }

  @protected
  ChapterInfoDto dco_decode_chapter_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChapterInfoDto(
      title: dco_decode_String(arr[0]),
      startTime: dco_decode_f_64(arr[1]),
      endTime: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  DownloadProgressDto dco_decode_download_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DownloadProgressDto(
      id: dco_decode_String(arr[0]),
      downloadedBytes: dco_decode_u_64(arr[1]),
      totalBytes: dco_decode_u_64(arr[2]),
      status: dco_decode_String(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<ChapterInfoDto> dco_decode_list_chapter_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_info_dto).toList();
  }

  @protected
  List<PlaylistVideoDto> dco_decode_list_playlist_video_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist_video_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SubtitleInfoDto> dco_decode_list_subtitle_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_subtitle_info_dto).toList();
  }

  @protected
  List<YouTubeSearchResultDto> dco_decode_list_you_tube_search_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_you_tube_search_result_dto).toList();
  }

  @protected
  List<YtDlpFormatDto> dco_decode_list_yt_dlp_format_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_yt_dlp_format_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  YtDlpProgressDto? dco_decode_opt_box_autoadd_yt_dlp_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_yt_dlp_progress_dto(raw);
  }

  @protected
  PlaylistInfoDto dco_decode_playlist_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8) throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PlaylistInfoDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      uploader: dco_decode_opt_String(arr[2]),
      uploaderId: dco_decode_opt_String(arr[3]),
      thumbnail: dco_decode_opt_String(arr[4]),
      description: dco_decode_opt_String(arr[5]),
      videoCount: dco_decode_opt_box_autoadd_u_32(arr[6]),
      webpageUrl: dco_decode_String(arr[7]),
    );
  }

  @protected
  PlaylistVideoDto dco_decode_playlist_video_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PlaylistVideoDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      url: dco_decode_String(arr[2]),
      thumbnail: dco_decode_opt_String(arr[3]),
      duration: dco_decode_opt_box_autoadd_u_64(arr[4]),
      channel: dco_decode_opt_String(arr[5]),
      channelId: dco_decode_opt_String(arr[6]),
      viewCount: dco_decode_opt_box_autoadd_u_64(arr[7]),
      uploadDate: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  (ChannelInfoDto, List<PlaylistVideoDto>) dco_decode_record_channel_info_dto_list_playlist_video_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_channel_info_dto(arr[0]), dco_decode_list_playlist_video_dto(arr[1]));
  }

  @protected
  (PlaylistInfoDto, List<PlaylistVideoDto>) dco_decode_record_playlist_info_dto_list_playlist_video_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_playlist_info_dto(arr[0]), dco_decode_list_playlist_video_dto(arr[1]));
  }

  @protected
  SubtitleInfoDto dco_decode_subtitle_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SubtitleInfoDto(
      lang: dco_decode_String(arr[0]),
      langName: dco_decode_opt_String(arr[1]),
      ext: dco_decode_String(arr[2]),
      url: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  YouTubeSearchResultDto dco_decode_you_tube_search_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10) throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return YouTubeSearchResultDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      channel: dco_decode_opt_String(arr[2]),
      channelId: dco_decode_opt_String(arr[3]),
      thumbnail: dco_decode_opt_String(arr[4]),
      duration: dco_decode_opt_box_autoadd_u_64(arr[5]),
      viewCount: dco_decode_opt_box_autoadd_u_64(arr[6]),
      uploadDate: dco_decode_opt_String(arr[7]),
      url: dco_decode_String(arr[8]),
      description: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  YtDlpFormatDto dco_decode_yt_dlp_format_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11) throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return YtDlpFormatDto(
      formatId: dco_decode_String(arr[0]),
      ext: dco_decode_String(arr[1]),
      resolution: dco_decode_opt_String(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
      width: dco_decode_opt_box_autoadd_u_32(arr[4]),
      filesize: dco_decode_opt_box_autoadd_u_64(arr[5]),
      vcodec: dco_decode_opt_String(arr[6]),
      acodec: dco_decode_opt_String(arr[7]),
      fps: dco_decode_opt_box_autoadd_f_64(arr[8]),
      tbr: dco_decode_opt_box_autoadd_f_64(arr[9]),
      formatNote: dco_decode_opt_String(arr[10]),
    );
  }

  @protected
  YtDlpProgressDto dco_decode_yt_dlp_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return YtDlpProgressDto(
      percent: dco_decode_f_64(arr[0]),
      downloadedBytes: dco_decode_opt_box_autoadd_u_64(arr[1]),
      totalBytes: dco_decode_opt_box_autoadd_u_64(arr[2]),
      speed: dco_decode_opt_box_autoadd_f_64(arr[3]),
      etaSeconds: dco_decode_opt_box_autoadd_u_64(arr[4]),
      status: dco_decode_String(arr[5]),
    );
  }

  @protected
  YtDlpVideoInfoDto dco_decode_yt_dlp_video_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18) throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return YtDlpVideoInfoDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      uploader: dco_decode_opt_String(arr[3]),
      uploaderId: dco_decode_opt_String(arr[4]),
      duration: dco_decode_opt_box_autoadd_u_64(arr[5]),
      viewCount: dco_decode_opt_box_autoadd_u_64(arr[6]),
      likeCount: dco_decode_opt_box_autoadd_u_64(arr[7]),
      uploadDate: dco_decode_opt_String(arr[8]),
      thumbnail: dco_decode_opt_String(arr[9]),
      webpageUrl: dco_decode_opt_String(arr[10]),
      extractor: dco_decode_opt_String(arr[11]),
      formats: dco_decode_list_yt_dlp_format_dto(arr[12]),
      subtitles: dco_decode_list_subtitle_info_dto(arr[13]),
      automaticCaptions: dco_decode_list_subtitle_info_dto(arr[14]),
      chapters: dco_decode_list_chapter_info_dto(arr[15]),
      isLive: dco_decode_bool(arr[16]),
      liveStatus: dco_decode_opt_String(arr[17]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  YtDlpProgressDto sse_decode_box_autoadd_yt_dlp_progress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_yt_dlp_progress_dto(deserializer));
  }

  @protected
  ChannelInfoDto sse_decode_channel_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_uploader = sse_decode_opt_String(deserializer);
    var var_uploaderId = sse_decode_opt_String(deserializer);
    var var_thumbnail = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_subscriberCount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_videoCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_webpageUrl = sse_decode_String(deserializer);
    return ChannelInfoDto(
      id: var_id,
      title: var_title,
      uploader: var_uploader,
      uploaderId: var_uploaderId,
      thumbnail: var_thumbnail,
      description: var_description,
      subscriberCount: var_subscriberCount,
      videoCount: var_videoCount,
      webpageUrl: var_webpageUrl,
    );
  }

  @protected
  ChapterInfoDto sse_decode_chapter_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_startTime = sse_decode_f_64(deserializer);
    var var_endTime = sse_decode_f_64(deserializer);
    return ChapterInfoDto(title: var_title, startTime: var_startTime, endTime: var_endTime);
  }

  @protected
  DownloadProgressDto sse_decode_download_progress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_downloadedBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return DownloadProgressDto(
      id: var_id,
      downloadedBytes: var_downloadedBytes,
      totalBytes: var_totalBytes,
      status: var_status,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<ChapterInfoDto> sse_decode_list_chapter_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistVideoDto> sse_decode_list_playlist_video_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistVideoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_video_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SubtitleInfoDto> sse_decode_list_subtitle_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SubtitleInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_subtitle_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<YouTubeSearchResultDto> sse_decode_list_you_tube_search_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <YouTubeSearchResultDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_you_tube_search_result_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<YtDlpFormatDto> sse_decode_list_yt_dlp_format_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <YtDlpFormatDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_yt_dlp_format_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  YtDlpProgressDto? sse_decode_opt_box_autoadd_yt_dlp_progress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_yt_dlp_progress_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaylistInfoDto sse_decode_playlist_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_uploader = sse_decode_opt_String(deserializer);
    var var_uploaderId = sse_decode_opt_String(deserializer);
    var var_thumbnail = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_videoCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_webpageUrl = sse_decode_String(deserializer);
    return PlaylistInfoDto(
      id: var_id,
      title: var_title,
      uploader: var_uploader,
      uploaderId: var_uploaderId,
      thumbnail: var_thumbnail,
      description: var_description,
      videoCount: var_videoCount,
      webpageUrl: var_webpageUrl,
    );
  }

  @protected
  PlaylistVideoDto sse_decode_playlist_video_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_channel = sse_decode_opt_String(deserializer);
    var var_channelId = sse_decode_opt_String(deserializer);
    var var_viewCount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_uploadDate = sse_decode_opt_String(deserializer);
    return PlaylistVideoDto(
      id: var_id,
      title: var_title,
      url: var_url,
      thumbnail: var_thumbnail,
      duration: var_duration,
      channel: var_channel,
      channelId: var_channelId,
      viewCount: var_viewCount,
      uploadDate: var_uploadDate,
    );
  }

  @protected
  (ChannelInfoDto, List<PlaylistVideoDto>) sse_decode_record_channel_info_dto_list_playlist_video_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_channel_info_dto(deserializer);
    var var_field1 = sse_decode_list_playlist_video_dto(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (PlaylistInfoDto, List<PlaylistVideoDto>) sse_decode_record_playlist_info_dto_list_playlist_video_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_playlist_info_dto(deserializer);
    var var_field1 = sse_decode_list_playlist_video_dto(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SubtitleInfoDto sse_decode_subtitle_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lang = sse_decode_String(deserializer);
    var var_langName = sse_decode_opt_String(deserializer);
    var var_ext = sse_decode_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    return SubtitleInfoDto(lang: var_lang, langName: var_langName, ext: var_ext, url: var_url);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  YouTubeSearchResultDto sse_decode_you_tube_search_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_channel = sse_decode_opt_String(deserializer);
    var var_channelId = sse_decode_opt_String(deserializer);
    var var_thumbnail = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_viewCount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_uploadDate = sse_decode_opt_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return YouTubeSearchResultDto(
      id: var_id,
      title: var_title,
      channel: var_channel,
      channelId: var_channelId,
      thumbnail: var_thumbnail,
      duration: var_duration,
      viewCount: var_viewCount,
      uploadDate: var_uploadDate,
      url: var_url,
      description: var_description,
    );
  }

  @protected
  YtDlpFormatDto sse_decode_yt_dlp_format_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_formatId = sse_decode_String(deserializer);
    var var_ext = sse_decode_String(deserializer);
    var var_resolution = sse_decode_opt_String(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_filesize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_vcodec = sse_decode_opt_String(deserializer);
    var var_acodec = sse_decode_opt_String(deserializer);
    var var_fps = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_tbr = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_formatNote = sse_decode_opt_String(deserializer);
    return YtDlpFormatDto(
      formatId: var_formatId,
      ext: var_ext,
      resolution: var_resolution,
      height: var_height,
      width: var_width,
      filesize: var_filesize,
      vcodec: var_vcodec,
      acodec: var_acodec,
      fps: var_fps,
      tbr: var_tbr,
      formatNote: var_formatNote,
    );
  }

  @protected
  YtDlpProgressDto sse_decode_yt_dlp_progress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_percent = sse_decode_f_64(deserializer);
    var var_downloadedBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_totalBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_speed = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_etaSeconds = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return YtDlpProgressDto(
      percent: var_percent,
      downloadedBytes: var_downloadedBytes,
      totalBytes: var_totalBytes,
      speed: var_speed,
      etaSeconds: var_etaSeconds,
      status: var_status,
    );
  }

  @protected
  YtDlpVideoInfoDto sse_decode_yt_dlp_video_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_uploader = sse_decode_opt_String(deserializer);
    var var_uploaderId = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_viewCount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_likeCount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_uploadDate = sse_decode_opt_String(deserializer);
    var var_thumbnail = sse_decode_opt_String(deserializer);
    var var_webpageUrl = sse_decode_opt_String(deserializer);
    var var_extractor = sse_decode_opt_String(deserializer);
    var var_formats = sse_decode_list_yt_dlp_format_dto(deserializer);
    var var_subtitles = sse_decode_list_subtitle_info_dto(deserializer);
    var var_automaticCaptions = sse_decode_list_subtitle_info_dto(deserializer);
    var var_chapters = sse_decode_list_chapter_info_dto(deserializer);
    var var_isLive = sse_decode_bool(deserializer);
    var var_liveStatus = sse_decode_opt_String(deserializer);
    return YtDlpVideoInfoDto(
      id: var_id,
      title: var_title,
      description: var_description,
      uploader: var_uploader,
      uploaderId: var_uploaderId,
      duration: var_duration,
      viewCount: var_viewCount,
      likeCount: var_likeCount,
      uploadDate: var_uploadDate,
      thumbnail: var_thumbnail,
      webpageUrl: var_webpageUrl,
      extractor: var_extractor,
      formats: var_formats,
      subtitles: var_subtitles,
      automaticCaptions: var_automaticCaptions,
      chapters: var_chapters,
      isLive: var_isLive,
      liveStatus: var_liveStatus,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_yt_dlp_progress_dto(YtDlpProgressDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_yt_dlp_progress_dto(self, serializer);
  }

  @protected
  void sse_encode_channel_info_dto(ChannelInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.uploader, serializer);
    sse_encode_opt_String(self.uploaderId, serializer);
    sse_encode_opt_String(self.thumbnail, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_u_64(self.subscriberCount, serializer);
    sse_encode_opt_box_autoadd_u_32(self.videoCount, serializer);
    sse_encode_String(self.webpageUrl, serializer);
  }

  @protected
  void sse_encode_chapter_info_dto(ChapterInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.startTime, serializer);
    sse_encode_f_64(self.endTime, serializer);
  }

  @protected
  void sse_encode_download_progress_dto(DownloadProgressDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_u_64(self.downloadedBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_chapter_info_dto(List<ChapterInfoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_video_dto(List<PlaylistVideoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_video_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_subtitle_info_dto(List<SubtitleInfoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_subtitle_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_you_tube_search_result_dto(List<YouTubeSearchResultDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_you_tube_search_result_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_yt_dlp_format_dto(List<YtDlpFormatDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_yt_dlp_format_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_yt_dlp_progress_dto(YtDlpProgressDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_yt_dlp_progress_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_playlist_info_dto(PlaylistInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.uploader, serializer);
    sse_encode_opt_String(self.uploaderId, serializer);
    sse_encode_opt_String(self.thumbnail, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_u_32(self.videoCount, serializer);
    sse_encode_String(self.webpageUrl, serializer);
  }

  @protected
  void sse_encode_playlist_video_dto(PlaylistVideoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.thumbnail, serializer);
    sse_encode_opt_box_autoadd_u_64(self.duration, serializer);
    sse_encode_opt_String(self.channel, serializer);
    sse_encode_opt_String(self.channelId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.viewCount, serializer);
    sse_encode_opt_String(self.uploadDate, serializer);
  }

  @protected
  void sse_encode_record_channel_info_dto_list_playlist_video_dto(
    (ChannelInfoDto, List<PlaylistVideoDto>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_channel_info_dto(self.$1, serializer);
    sse_encode_list_playlist_video_dto(self.$2, serializer);
  }

  @protected
  void sse_encode_record_playlist_info_dto_list_playlist_video_dto(
    (PlaylistInfoDto, List<PlaylistVideoDto>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_playlist_info_dto(self.$1, serializer);
    sse_encode_list_playlist_video_dto(self.$2, serializer);
  }

  @protected
  void sse_encode_subtitle_info_dto(SubtitleInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lang, serializer);
    sse_encode_opt_String(self.langName, serializer);
    sse_encode_String(self.ext, serializer);
    sse_encode_opt_String(self.url, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_you_tube_search_result_dto(YouTubeSearchResultDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.channel, serializer);
    sse_encode_opt_String(self.channelId, serializer);
    sse_encode_opt_String(self.thumbnail, serializer);
    sse_encode_opt_box_autoadd_u_64(self.duration, serializer);
    sse_encode_opt_box_autoadd_u_64(self.viewCount, serializer);
    sse_encode_opt_String(self.uploadDate, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_yt_dlp_format_dto(YtDlpFormatDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.formatId, serializer);
    sse_encode_String(self.ext, serializer);
    sse_encode_opt_String(self.resolution, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_64(self.filesize, serializer);
    sse_encode_opt_String(self.vcodec, serializer);
    sse_encode_opt_String(self.acodec, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fps, serializer);
    sse_encode_opt_box_autoadd_f_64(self.tbr, serializer);
    sse_encode_opt_String(self.formatNote, serializer);
  }

  @protected
  void sse_encode_yt_dlp_progress_dto(YtDlpProgressDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.percent, serializer);
    sse_encode_opt_box_autoadd_u_64(self.downloadedBytes, serializer);
    sse_encode_opt_box_autoadd_u_64(self.totalBytes, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speed, serializer);
    sse_encode_opt_box_autoadd_u_64(self.etaSeconds, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_yt_dlp_video_info_dto(YtDlpVideoInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.uploader, serializer);
    sse_encode_opt_String(self.uploaderId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.duration, serializer);
    sse_encode_opt_box_autoadd_u_64(self.viewCount, serializer);
    sse_encode_opt_box_autoadd_u_64(self.likeCount, serializer);
    sse_encode_opt_String(self.uploadDate, serializer);
    sse_encode_opt_String(self.thumbnail, serializer);
    sse_encode_opt_String(self.webpageUrl, serializer);
    sse_encode_opt_String(self.extractor, serializer);
    sse_encode_list_yt_dlp_format_dto(self.formats, serializer);
    sse_encode_list_subtitle_info_dto(self.subtitles, serializer);
    sse_encode_list_subtitle_info_dto(self.automaticCaptions, serializer);
    sse_encode_list_chapter_info_dto(self.chapters, serializer);
    sse_encode_bool(self.isLive, serializer);
    sse_encode_opt_String(self.liveStatus, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
