import 'video_info.dart';

enum DownloadFileType {
  video,
  audio,
  image,
  subtitle;

  String toDbString() => name;

  MediaType toMediaType() {
    switch (this) {
      case DownloadFileType.video:
        return MediaType.video;
      case DownloadFileType.audio:
        return MediaType.audio;
      case DownloadFileType.image:
        return MediaType.image;
      case DownloadFileType.subtitle:
        return MediaType.subtitle;
    }
  }

  static DownloadFileType fromMediaType(MediaType mediaType) {
    switch (mediaType) {
      case MediaType.video:
        return DownloadFileType.video;
      case MediaType.audio:
        return DownloadFileType.audio;
      case MediaType.image:
        return DownloadFileType.image;
      case MediaType.subtitle:
        return DownloadFileType.subtitle;
    }
  }

  static DownloadFileType fromDbString(String value) {
    return DownloadFileType.values.firstWhere(
      (type) => type.name == value,
      orElse: () => DownloadFileType.video,
    );
  }
}

enum DownloadQualityIntent {
  recommended,
  bestAvailable,
  specific,
  technicalStream;

  String toDbString() => name;

  static DownloadQualityIntent fromDbString(String value) {
    return DownloadQualityIntent.values.firstWhere(
      (intent) => intent.name == value,
      orElse: () => DownloadQualityIntent.recommended,
    );
  }
}

enum ImageSelectionMode {
  all;

  String toDbString() => name;

  static ImageSelectionMode fromDbString(String value) {
    return ImageSelectionMode.values.firstWhere(
      (mode) => mode.name == value,
      orElse: () => ImageSelectionMode.all,
    );
  }
}

class PortableQualityTarget {
  final DownloadFileType fileType;
  final int? targetHeight;
  final int? targetFpsCap;
  final String? outputFormat;
  final int? targetBitrateKbps;
  final String? languageCode;
  final bool? isAutoGenerated;
  final String? subtitleFormat;
  final ImageSelectionMode? imageSelectionMode;

  const PortableQualityTarget.video({
    required int this.targetHeight,
    this.targetFpsCap,
  }) : fileType = DownloadFileType.video,
       outputFormat = null,
       targetBitrateKbps = null,
       languageCode = null,
       isAutoGenerated = null,
       subtitleFormat = null,
       imageSelectionMode = null;

  const PortableQualityTarget.audio({
    required String this.outputFormat,
    this.targetBitrateKbps,
  }) : fileType = DownloadFileType.audio,
       targetHeight = null,
       targetFpsCap = null,
       languageCode = null,
       isAutoGenerated = null,
       subtitleFormat = null,
       imageSelectionMode = null;

  const PortableQualityTarget.subtitle({
    required String this.languageCode,
    required String this.subtitleFormat,
    this.isAutoGenerated = false,
  }) : fileType = DownloadFileType.subtitle,
       targetHeight = null,
       targetFpsCap = null,
       outputFormat = null,
       targetBitrateKbps = null,
       imageSelectionMode = null;

  const PortableQualityTarget.image({
    this.imageSelectionMode = ImageSelectionMode.all,
  }) : fileType = DownloadFileType.image,
       targetHeight = null,
       targetFpsCap = null,
       outputFormat = null,
       targetBitrateKbps = null,
       languageCode = null,
       isAutoGenerated = null,
       subtitleFormat = null;

  Map<String, dynamic> toJson() {
    return {
      'fileType': fileType.toDbString(),
      if (targetHeight != null) 'targetHeight': targetHeight,
      if (targetFpsCap != null) 'targetFpsCap': targetFpsCap,
      if (outputFormat != null) 'outputFormat': outputFormat,
      if (targetBitrateKbps != null) 'targetBitrateKbps': targetBitrateKbps,
      if (languageCode != null) 'languageCode': languageCode,
      if (isAutoGenerated != null) 'isAutoGenerated': isAutoGenerated,
      if (subtitleFormat != null) 'subtitleFormat': subtitleFormat,
      if (imageSelectionMode != null)
        'imageSelectionMode': imageSelectionMode!.toDbString(),
    };
  }

  factory PortableQualityTarget.fromJson(Map<String, dynamic> json) {
    final fileType = DownloadFileType.fromDbString(
      json['fileType'] as String? ?? DownloadFileType.video.name,
    );
    switch (fileType) {
      case DownloadFileType.video:
        return PortableQualityTarget.video(
          targetHeight: json['targetHeight'] as int? ?? 1080,
          targetFpsCap: json['targetFpsCap'] as int?,
        );
      case DownloadFileType.audio:
        return PortableQualityTarget.audio(
          outputFormat: json['outputFormat'] as String? ?? 'mp3',
          targetBitrateKbps: json['targetBitrateKbps'] as int?,
        );
      case DownloadFileType.subtitle:
        return PortableQualityTarget.subtitle(
          languageCode: json['languageCode'] as String? ?? 'en',
          subtitleFormat: json['subtitleFormat'] as String? ?? 'srt',
          isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
        );
      case DownloadFileType.image:
        return PortableQualityTarget.image(
          imageSelectionMode: ImageSelectionMode.fromDbString(
            json['imageSelectionMode'] as String? ??
                ImageSelectionMode.all.name,
          ),
        );
    }
  }

  @override
  bool operator ==(Object other) {
    return other is PortableQualityTarget &&
        other.fileType == fileType &&
        other.targetHeight == targetHeight &&
        other.targetFpsCap == targetFpsCap &&
        other.outputFormat == outputFormat &&
        other.targetBitrateKbps == targetBitrateKbps &&
        other.languageCode == languageCode &&
        other.isAutoGenerated == isAutoGenerated &&
        other.subtitleFormat == subtitleFormat &&
        other.imageSelectionMode == imageSelectionMode;
  }

  @override
  int get hashCode => Object.hash(
    fileType,
    targetHeight,
    targetFpsCap,
    outputFormat,
    targetBitrateKbps,
    languageCode,
    isAutoGenerated,
    subtitleFormat,
    imageSelectionMode,
  );
}
