import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../../core/l10n/app_localizations.dart';

part 'video_info.freezed.dart';

/// Chapter information for video
@freezed
class ChapterInfo with _$ChapterInfo {
  const ChapterInfo._();

  const factory ChapterInfo({
    required String title,
    required double startTime, // seconds
    required double endTime, // seconds
  }) = _ChapterInfo;

  /// Get chapter duration
  Duration get duration => Duration(seconds: (endTime - startTime).round());

  /// Format start time as HH:MM:SS or MM:SS
  String get formattedStartTime {
    final totalSeconds = startTime.round();
    final hours = totalSeconds ~/ 3600;
    final minutes = (totalSeconds % 3600) ~/ 60;
    final seconds = totalSeconds % 60;

    if (hours > 0) {
      return '${hours.toString().padLeft(2, '0')}:${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
    }
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }

  /// Format duration as MM:SS
  String get formattedDuration {
    final totalSeconds = (endTime - startTime).round();
    final minutes = totalSeconds ~/ 60;
    final seconds = totalSeconds % 60;
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }
}

/// Subtitle track information from yt-dlp extraction
class SubtitleTrackInfo {
  final String lang; // e.g. 'en', 'ja', 'vi'
  final String langName; // e.g. 'English', 'Japanese', 'Vietnamese'
  final bool isAutoGenerated;

  const SubtitleTrackInfo({
    required this.lang,
    required this.langName,
    this.isAutoGenerated = false,
  });

  String get displayName => langName.isNotEmpty ? '$langName ($lang)' : lang;
}

/// Video information extracted from URL
@freezed
class VideoInfo with _$VideoInfo {
  const VideoInfo._();

  const factory VideoInfo({
    required String url,
    required String title,
    String? thumbnail,
    String? extractor, // "tiktok", "facebook", "youtube", etc.
    Author? author,
    required List<Quality> availableQualities,
    List<GalleryItem>? galleryItems, // For carousel posts

    // Rich metadata (added for yt-dlp integration)
    String? description,
    Duration? duration,
    String? platform, // Normalized platform name (youtube, tiktok, etc.)
    String? uploader, // Channel/uploader name
    int? viewCount,
    DateTime? uploadDate,
    @Default('unknown') String downloadMethod, // 'ytdlp', 'api', 'unknown'

    // P1 features
    @Default([]) List<ChapterInfo> chapters, // Video chapters
    @Default(false) bool isLive, // Live stream indicator
    String? liveStatus, // is_live, was_live, is_upcoming

    // Subtitle availability from extraction
    @Default([]) List<SubtitleTrackInfo> availableSubtitles, // Human-written
    @Default([]) List<SubtitleTrackInfo> availableAutoSubtitles, // Auto-generated
  }) = _VideoInfo;

  bool get hasMultipleQualities => availableQualities.length > 1;
  bool get isCarousel => galleryItems != null && galleryItems!.isNotEmpty;
  bool get hasChapters => chapters.isNotEmpty;
  bool get isLiveStream => isLive || liveStatus == 'is_live';
  bool get wasLive => liveStatus == 'was_live';
  bool get isUpcoming => liveStatus == 'is_upcoming';
  bool get hasSubtitleInfo =>
      availableSubtitles.isNotEmpty || availableAutoSubtitles.isNotEmpty;
  List<String> get subtitleLanguages =>
      availableSubtitles.map((s) => s.lang).toList();

  /// Get effective platform name (from platform or extractor)
  String get effectivePlatform => platform ?? extractor ?? 'unknown';

  /// Get effective uploader name (from uploader or author)
  String? get effectiveUploader => uploader ?? author?.username;
}

/// Quality option for download
@freezed
class Quality with _$Quality {
  const Quality._();

  const factory Quality({
    required String qualityText, // "MP4 720p [720x1280]"
    required String size, // "1.9 MB"
    required String encryptedUrl, // Token to decode (or conversion key for YouTube)
    required MediaType mediaType,
    String? conversionKey, // YouTube conversion key (stored in encryptedUrl for consistency)
    bool? isYouTube, // Flag to indicate YouTube quality
    // Raw format metadata for advanced stream selection
    String? vcodec, // 'h264', 'vp9', 'av1'
    String? acodec, // 'aac', 'opus'
    double? fps, // 30.0, 60.0
    @Default(false) bool isVideoOnly, // true = no audio track
    @Default(false) bool isAudioOnly, // true = no video track
    double? tbr, // total bitrate kbps
    int? filesizeBytes, // raw file size in bytes (null if unknown)
  }) = _Quality;

  String get displayText => qualityText;
  String get displaySize => size.isNotEmpty ? size : 'Unknown size';
}

enum MediaType {
  video,
  audio,
  image,
  subtitle;

  /// Locale-aware display label resolved via AppLocalizations.
  /// Stable enum.name maps to `mediaType.<name>` i18n key.
  String get displayName => AppLocalizations.mediaTypeLabel(name);
}

/// Author information
@freezed
class Author with _$Author {
  const factory Author({
    required String username,
    String? fullName,
    String? avatar,
  }) = _Author;
}

/// Gallery item for carousel posts
@freezed
class GalleryItem with _$GalleryItem {
  const factory GalleryItem({
    String? id,
    required MediaType mediaType,
    String? thumbnail,
    String? label,
    required List<Resource> resources,
  }) = _GalleryItem;
}

/// Resource (different sizes/qualities of gallery item)
@freezed
class Resource with _$Resource {
  const factory Resource({
    String? resolution, // "1080x1440"
    required String encryptedUrl,
  }) = _Resource;
}
