import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import '../../../../core/logging/app_logger.dart';
import '../../domain/entities/video_info.dart';

/// Cache entry with metadata
class CacheEntry {
  final VideoInfo videoInfo;
  final DateTime extractedAt;
  final DateTime lastAccessedAt;

  CacheEntry({
    required this.videoInfo,
    required this.extractedAt,
    DateTime? lastAccessedAt,
  }) : lastAccessedAt = lastAccessedAt ?? extractedAt;

  CacheEntry copyWithAccess() {
    return CacheEntry(
      videoInfo: videoInfo,
      extractedAt: extractedAt,
      lastAccessedAt: DateTime.now(),
    );
  }

  bool get isExpired {
    return DateTime.now().difference(extractedAt) > ExtractionCache.ttl;
  }

  Map<String, dynamic> toJson() {
    return {
      'videoInfo': _videoInfoToJson(videoInfo),
      'extractedAt': extractedAt.toIso8601String(),
      'lastAccessedAt': lastAccessedAt.toIso8601String(),
    };
  }

  factory CacheEntry.fromJson(Map<String, dynamic> json) {
    return CacheEntry(
      videoInfo: _videoInfoFromJson(json['videoInfo']),
      extractedAt: DateTime.parse(json['extractedAt']),
      lastAccessedAt: DateTime.parse(json['lastAccessedAt']),
    );
  }

  static Map<String, dynamic> _videoInfoToJson(VideoInfo info) {
    return {
      'url': info.url,
      'title': info.title,
      'description': info.description,
      'thumbnail': info.thumbnail,
      'duration': info.duration?.inSeconds,
      'platform': info.platform,
      'uploader': info.uploader,
      'viewCount': info.viewCount,
      'uploadDate': info.uploadDate?.toIso8601String(),
      'extractor': info.extractor,
      'downloadMethod': info.downloadMethod,
      'author': info.author != null
          ? {
              'username': info.author!.username,
              'fullName': info.author!.fullName,
              'avatar': info.author!.avatar,
            }
          : null,
      'qualities': info.availableQualities.map((q) => {
        'qualityText': q.qualityText,
        'size': q.size,
        'encryptedUrl': q.encryptedUrl,
        'mediaType': q.mediaType.name,
        'isYouTube': q.isYouTube,
        'conversionKey': q.conversionKey,
        'vcodec': q.vcodec,
        'acodec': q.acodec,
        'fps': q.fps,
        'isVideoOnly': q.isVideoOnly,
        'isAudioOnly': q.isAudioOnly,
        'tbr': q.tbr,
        'filesizeBytes': q.filesizeBytes,
      }).toList(),
      'galleryItems': info.galleryItems?.map((g) => {
        'id': g.id,
        'mediaType': g.mediaType.name,
        'thumbnail': g.thumbnail,
        'label': g.label,
        'resources': g.resources.map((r) => {
          'resolution': r.resolution,
          'encryptedUrl': r.encryptedUrl,
        }).toList(),
      }).toList(),
      // Chapters — required so the per-chapter selection UI in the download
      // config dialog still works after the videoInfo is rehydrated from
      // cache (within the 1-hour TTL). Missing this previously caused the
      // chapter section to silently disappear on cache hit.
      'chapters': info.chapters
          .map((c) => {
                'title': c.title,
                'startTime': c.startTime,
                'endTime': c.endTime,
              })
          .toList(),
      'isLive': info.isLive,
      'liveStatus': info.liveStatus,
      'availableSubtitles': info.availableSubtitles
          .map((s) => {
                'lang': s.lang,
                'langName': s.langName,
                'isAutoGenerated': s.isAutoGenerated,
              })
          .toList(),
      'availableAutoSubtitles': info.availableAutoSubtitles
          .map((s) => {
                'lang': s.lang,
                'langName': s.langName,
                'isAutoGenerated': s.isAutoGenerated,
              })
          .toList(),
    };
  }

  static VideoInfo _videoInfoFromJson(Map<String, dynamic> json) {
    return VideoInfo(
      url: json['url'] ?? '',
      title: json['title'] ?? '',
      description: json['description'],
      thumbnail: json['thumbnail'],
      duration: json['duration'] != null
          ? Duration(seconds: json['duration'])
          : null,
      platform: json['platform'] ?? 'unknown',
      uploader: json['uploader'],
      viewCount: json['viewCount'],
      uploadDate: json['uploadDate'] != null
          ? DateTime.tryParse(json['uploadDate'])
          : null,
      extractor: json['extractor'],
      downloadMethod: json['downloadMethod'] ?? 'unknown',
      author: json['author'] != null
          ? Author(
              username: json['author']['username'] ?? '',
              fullName: json['author']['fullName'],
              avatar: json['author']['avatar'],
            )
          : null,
      availableQualities: (json['qualities'] as List?)?.map((q) => Quality(
        qualityText: q['qualityText'] ?? '',
        size: q['size'] ?? '',
        encryptedUrl: q['encryptedUrl'] ?? '',
        mediaType: MediaType.values.firstWhere(
          (m) => m.name == q['mediaType'],
          orElse: () => MediaType.video,
        ),
        isYouTube: q['isYouTube'],
        conversionKey: q['conversionKey'],
        vcodec: q['vcodec'],
        acodec: q['acodec'],
        fps: (q['fps'] as num?)?.toDouble(),
        isVideoOnly: q['isVideoOnly'] ?? false,
        isAudioOnly: q['isAudioOnly'] ?? false,
        tbr: (q['tbr'] as num?)?.toDouble(),
        filesizeBytes: q['filesizeBytes'],
      )).toList() ?? [],
      galleryItems: (json['galleryItems'] as List?)?.map((g) => GalleryItem(
        id: g['id'],
        mediaType: MediaType.values.firstWhere(
          (m) => m.name == g['mediaType'],
          orElse: () => MediaType.video,
        ),
        thumbnail: g['thumbnail'],
        label: g['label'],
        resources: (g['resources'] as List?)?.map((r) => Resource(
          resolution: r['resolution'],
          encryptedUrl: r['encryptedUrl'] ?? '',
        )).toList() ?? [],
      )).toList(),
      chapters: (json['chapters'] as List?)
              ?.map((c) => ChapterInfo(
                    title: c['title'] ?? '',
                    startTime: (c['startTime'] as num?)?.toDouble() ?? 0.0,
                    endTime: (c['endTime'] as num?)?.toDouble() ?? 0.0,
                  ))
              .toList() ??
          const [],
      isLive: json['isLive'] ?? false,
      liveStatus: json['liveStatus'],
      availableSubtitles: (json['availableSubtitles'] as List?)
              ?.map((s) => SubtitleTrackInfo(
                    lang: s['lang'] ?? '',
                    langName: s['langName'] ?? '',
                    isAutoGenerated: s['isAutoGenerated'] ?? false,
                  ))
              .toList() ??
          const [],
      availableAutoSubtitles: (json['availableAutoSubtitles'] as List?)
              ?.map((s) => SubtitleTrackInfo(
                    lang: s['lang'] ?? '',
                    langName: s['langName'] ?? '',
                    isAutoGenerated: s['isAutoGenerated'] ?? true,
                  ))
              .toList() ??
          const [],
    );
  }
}

/// LRU Cache for extracted video info
/// - Max 100 URLs
/// - TTL 1 hour
/// - Persists to SharedPreferences
class ExtractionCache {
  // v2 — added chapters / live status / subtitles to the serialized payload.
  // Bumping the key invalidates v1 cache entries that lack `chapters` and
  // would otherwise hide the per-chapter selection UI on cache hit.
  static const String _storageKey = 'extraction_cache_v2';
  static const int maxSize = 100;
  static const Duration ttl = Duration(hours: 1);

  final SharedPreferences _prefs;
  final Map<String, CacheEntry> _cache = {};
  bool _initialized = false;

  ExtractionCache(this._prefs);

  /// Initialize cache from storage
  Future<void> initialize() async {
    if (_initialized) return;

    try {
      final jsonStr = _prefs.getString(_storageKey);
      if (jsonStr != null) {
        final Map<String, dynamic> data = json.decode(jsonStr);
        for (final entry in data.entries) {
          try {
            final cacheEntry = CacheEntry.fromJson(entry.value);
            // Skip expired entries
            if (!cacheEntry.isExpired) {
              _cache[entry.key] = cacheEntry;
            }
          } catch (_) {
            // Skip invalid entries
          }
        }
      }
    } catch (_) {
      // Start with empty cache if load fails
    }

    _initialized = true;
  }

  /// Check if cache is initialized
  bool get isInitialized => _initialized;

  /// Get cached video info (returns null if not found, expired, or not initialized)
  /// Note: Call initialize() first or use getAsync() for async initialization
  VideoInfo? get(String url) {
    // Return null if not initialized yet (caller should await initialize first)
    if (!_initialized) return null;

    final normalizedUrl = _normalizeUrl(url);
    final entry = _cache[normalizedUrl];

    if (entry == null) return null;

    // Check expiration
    if (entry.isExpired) {
      _cache.remove(normalizedUrl);
      _persist();
      return null;
    }

    // Update last accessed time (LRU)
    _cache[normalizedUrl] = entry.copyWithAccess();
    _persist();

    return entry.videoInfo;
  }

  /// Async version that ensures initialization before getting
  Future<VideoInfo?> getAsync(String url) async {
    await initialize();
    return get(url);
  }

  /// Store video info in cache
  Future<void> set(String url, VideoInfo info) async {
    await initialize();

    final normalizedUrl = _normalizeUrl(url);

    // Check if we need to evict (LRU)
    if (_cache.length >= maxSize && !_cache.containsKey(normalizedUrl)) {
      _evictLRU();
    }

    _cache[normalizedUrl] = CacheEntry(
      videoInfo: info,
      extractedAt: DateTime.now(),
    );

    await _persist();
  }

  /// Get all cached entries (sorted by last accessed, newest first)
  List<CacheEntry> getAll() {
    // Remove expired entries first
    _cache.removeWhere((_, entry) => entry.isExpired);

    final entries = _cache.values.toList();
    entries.sort((a, b) => b.lastAccessedAt.compareTo(a.lastAccessedAt));
    return entries;
  }

  /// Get history items for UI (non-expired, sorted by extraction time)
  List<CacheEntry> getHistory() {
    _cache.removeWhere((_, entry) => entry.isExpired);

    final entries = _cache.values.toList();
    entries.sort((a, b) => b.extractedAt.compareTo(a.extractedAt));
    return entries;
  }

  /// Remove specific URL from cache
  Future<void> remove(String url) async {
    final normalizedUrl = _normalizeUrl(url);
    _cache.remove(normalizedUrl);
    await _persist();
  }

  /// Clear all cache
  Future<void> clear() async {
    _cache.clear();
    await _prefs.remove(_storageKey);
  }

  /// Get cache size
  int get size => _cache.length;

  /// Check if URL is cached (and not expired)
  bool contains(String url) {
    final normalizedUrl = _normalizeUrl(url);
    final entry = _cache[normalizedUrl];
    if (entry == null) return false;
    if (entry.isExpired) {
      _cache.remove(normalizedUrl);
      return false;
    }
    return true;
  }

  /// Evict least recently used entry
  void _evictLRU() {
    if (_cache.isEmpty) return;

    String? lruKey;
    DateTime? lruTime;

    for (final entry in _cache.entries) {
      if (lruTime == null || entry.value.lastAccessedAt.isBefore(lruTime)) {
        lruTime = entry.value.lastAccessedAt;
        lruKey = entry.key;
      }
    }

    if (lruKey != null) {
      _cache.remove(lruKey);
    }
  }

  /// Normalize URL for consistent caching.
  ///
  /// Canonicalizes platform-specific URL variants so the same content
  /// always maps to the same cache key:
  /// - YouTube: youtu.be/X, /shorts/X, m.youtube.com → youtube.com/watch?v=X
  /// - Twitter/X: x.com → twitter.com
  String _normalizeUrl(String url) {
    var normalized = url.trim();
    while (normalized.endsWith('/')) {
      normalized = normalized.substring(0, normalized.length - 1);
    }

    final uri = Uri.tryParse(normalized);
    if (uri == null) return normalized;

    // Canonicalize platform URLs before param cleanup
    final canonical = _canonicalizePlatformUrl(uri);

    // Remove tracking params
    final params = Map<String, String>.from(canonical.queryParameters);
    params.remove('utm_source');
    params.remove('utm_medium');
    params.remove('utm_campaign');
    params.remove('feature');
    params.remove('si');
    params.remove('fbclid');
    params.remove('ref');

    return canonical.replace(queryParameters: params.isEmpty ? null : params).toString();
  }

  /// Canonicalize platform-specific URL variants to a single form.
  static Uri _canonicalizePlatformUrl(Uri uri) {
    final host = uri.host.toLowerCase();

    // YouTube: all forms → youtube.com/watch?v=ID
    if (host == 'youtu.be') {
      // youtu.be/VIDEO_ID → youtube.com/watch?v=VIDEO_ID
      final videoId = uri.pathSegments.isNotEmpty ? uri.pathSegments.first : null;
      if (videoId != null && videoId.isNotEmpty) {
        return Uri.parse('https://www.youtube.com/watch?v=$videoId');
      }
    }
    if (host.contains('youtube.com')) {
      final path = uri.path;
      String? videoId;

      // /shorts/VIDEO_ID or /embed/VIDEO_ID or /v/VIDEO_ID
      final shortMatch = RegExp(r'^/(shorts|embed|v)/([a-zA-Z0-9_-]+)').firstMatch(path);
      if (shortMatch != null) {
        videoId = shortMatch.group(2);
      }
      // /watch?v=VIDEO_ID (just normalize host)
      videoId ??= uri.queryParameters['v'];

      if (videoId != null && videoId.isNotEmpty) {
        return Uri.parse('https://www.youtube.com/watch?v=$videoId');
      }
      // Non-video YouTube URL (channel, playlist) — just normalize host
      return uri.replace(host: 'www.youtube.com');
    }

    // Twitter/X: x.com → twitter.com
    if (host == 'x.com' || host == 'www.x.com') {
      return uri.replace(host: 'twitter.com');
    }

    // Instagram: www prefix normalization
    if (host == 'instagram.com') {
      return uri.replace(host: 'www.instagram.com');
    }

    // TikTok: www prefix normalization (short URLs can't be canonicalized without redirect)
    if (host == 'tiktok.com') {
      return uri.replace(host: 'www.tiktok.com');
    }

    return uri;
  }

  /// Persist cache to SharedPreferences
  Future<void> _persist() async {
    try {
      final Map<String, dynamic> data = {};
      for (final entry in _cache.entries) {
        data[entry.key] = entry.value.toJson();
      }
      await _prefs.setString(_storageKey, json.encode(data));
    } catch (e) {
      appLogger.warning('Cache persist failed: $e');
    }
  }
}
