#!/bin/bash
# set_brand.sh — Switch macOS/Windows/Linux build config to a specific brand.
# Usage: ./scripts/set_brand.sh [svid|vidcombo]
# Default: svid
#
# Updates: AppInfo.xcconfig, CMakeLists.txt BINARY_NAME, brand_config.h,
#          macOS app icon set, Windows/Linux icons
# Run BEFORE flutter build.

set -euo pipefail

BRAND="${1:-svid}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Cross-platform sed -i (macOS requires '' arg, GNU sed does not)
sedi() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# Validate brand
if [[ "$BRAND" != "svid" && "$BRAND" != "vidcombo" ]]; then
  echo "Error: Unknown brand '$BRAND'. Use 'svid' or 'vidcombo'."
  exit 1
fi

echo "Setting brand: $BRAND"

# === macOS: Update AppInfo.xcconfig include ===
APPINFO="$ROOT_DIR/macos/Runner/Configs/AppInfo.xcconfig"
BRAND_CONFIG="$ROOT_DIR/macos/Runner/Configs/brands/$BRAND.xcconfig"

if [[ -f "$BRAND_CONFIG" ]]; then
  sedi "s|#include \"brands/.*\\.xcconfig\"|#include \"brands/$BRAND.xcconfig\"|" "$APPINFO"
  echo "  macOS: AppInfo.xcconfig → brands/$BRAND.xcconfig"
fi

# === macOS: Generate app icon sizes from brand's 1024x1024 logo ===
# Bug history: previously this used `cp` for the 1024 size, which silently
# copied a 512×512 source as `app_icon_1024.png`. iconutil then DROPS files
# whose actual dimensions don't match the Contents.json declaration → macOS
# falls back to a generic icon at retina sizes. Now we always resample with
# sips so the file is genuinely the size its name claims, and we verify.
BRAND_LOGO="$ROOT_DIR/assets/brands/$BRAND/app_icon.png"
APPICON_DIR="$ROOT_DIR/macos/Runner/Assets.xcassets/AppIcon.appiconset"
if [[ -f "$BRAND_LOGO" ]] && command -v sips &>/dev/null; then
  # Verify source is at least 1024×1024 — anything smaller will be upscaled
  # blurry and Apple Store rejects icons under 1024.
  SRC_W=$(sips -g pixelWidth "$BRAND_LOGO" 2>/dev/null | awk '/pixelWidth/ {print $2}')
  SRC_H=$(sips -g pixelHeight "$BRAND_LOGO" 2>/dev/null | awk '/pixelHeight/ {print $2}')
  if [[ -z "$SRC_W" || -z "$SRC_H" ]]; then
    echo "  ERROR: cannot read dimensions of $BRAND_LOGO" >&2
    exit 1
  fi
  if (( SRC_W < 1024 || SRC_H < 1024 )); then
    echo "  ERROR: $BRAND_LOGO is ${SRC_W}x${SRC_H} — need at least 1024x1024" >&2
    echo "         Replace assets/brands/$BRAND/app_icon.png with a 1024x1024 PNG." >&2
    exit 1
  fi

  for size in 16 32 64 128 256 512 1024; do
    sips -z $size $size "$BRAND_LOGO" --out "$APPICON_DIR/app_icon_${size}.png" >/dev/null 2>&1
  done

  # Verify each generated file matches its declared size — defends against
  # silent iconutil drops downstream.
  for size in 16 32 64 128 256 512 1024; do
    target="$APPICON_DIR/app_icon_${size}.png"
    actual_w=$(sips -g pixelWidth "$target" 2>/dev/null | awk '/pixelWidth/ {print $2}')
    if [[ "$actual_w" != "$size" ]]; then
      echo "  ERROR: $target is ${actual_w}px wide, expected ${size}px" >&2
      exit 1
    fi
  done

  echo "  macOS: App icons generated from brands/$BRAND/ (7 sizes, verified)"
fi

# === Windows: Update CMakeLists.txt project name + BINARY_NAME ===
CMAKE="$ROOT_DIR/windows/CMakeLists.txt"
if [[ -f "$CMAKE" ]]; then
  if [[ "$BRAND" == "vidcombo" ]]; then
    sedi 's/project(svid /project(vidcombo /' "$CMAKE"
    sedi 's/set(BINARY_NAME "svid")/set(BINARY_NAME "vidcombo")/' "$CMAKE"
  else
    sedi 's/project(vidcombo /project(svid /' "$CMAKE"
    sedi 's/set(BINARY_NAME "vidcombo")/set(BINARY_NAME "svid")/' "$CMAKE"
  fi
  echo "  Windows: CMakeLists.txt project + BINARY_NAME updated"
fi

# === Windows: Generate brand_config.h ===
BRAND_H="$ROOT_DIR/windows/runner/brand_config.h"
if [[ "$BRAND" == "vidcombo" ]]; then
  cat > "$BRAND_H" << 'HEADER'
// Brand configuration for Windows build — VidCombo
// Generated by scripts/set_brand.sh

#ifndef BRAND_CONFIG_H_
#define BRAND_CONFIG_H_

#define BRAND_NAME "VidCombo"
#define BRAND_NAME_LOWER "vidcombo"
#define BRAND_NAME_WIDE L"VidCombo"
#define BRAND_WINDOW_CLASS_NAME L"VidCombo_WIN32_WINDOW"
#define BRAND_EXE_NAME "vidcombo.exe"
#define BRAND_URL_SCHEME "vidcombo://"
#define BRAND_BUNDLE_ID "com.tinasoft.vidcombo"
// Windows taskbar identity is intentionally separate from the bundle ID.
// Older BLUEBYTE/Tinasoft VidCombo installs and pins used the bundle-like
// identifier, which lets Windows keep serving stale pinned/taskbar icons even
// after the new exe embeds the correct icon. Keep this value stable going
// forward, but do not collapse it back to BRAND_BUNDLE_ID.
#define BRAND_APP_USER_MODEL_ID L"com.tinasoft.vidcombo.desktop"
#define BRAND_COMPANY_NAME "Bui Xuan Mai"
#define BRAND_PRODUCT_NAME "VidCombo Desktop"
#define BRAND_FILE_DESCRIPTION "VidCombo Desktop"
#define BRAND_COPYRIGHT "Copyright (C) 2026 Bui Xuan Mai. All rights reserved."
#define BRAND_PUBLISHER "VidCombo"
#define BRAND_DARK_BG_R 13
#define BRAND_DARK_BG_G 15
#define BRAND_DARK_BG_B 17
#define BRAND_LIGHT_BG_R 245
#define BRAND_LIGHT_BG_G 246
#define BRAND_LIGHT_BG_B 248
#define BRAND_DEFAULT_DARK 0

#endif  // BRAND_CONFIG_H_
HEADER
else
  cat > "$BRAND_H" << 'HEADER'
// Brand configuration for Windows build — Svid (default)
// Generated by scripts/set_brand.sh

#ifndef BRAND_CONFIG_H_
#define BRAND_CONFIG_H_

#define BRAND_NAME "Svid"
#define BRAND_NAME_LOWER "svid"
#define BRAND_NAME_WIDE L"Svid"
#define BRAND_WINDOW_CLASS_NAME L"Svid_WIN32_WINDOW"
#define BRAND_EXE_NAME "svid.exe"
#define BRAND_URL_SCHEME "svid://"
#define BRAND_BUNDLE_ID "com.svid.app"
#define BRAND_APP_USER_MODEL_ID L"com.svid.app"
#define BRAND_COMPANY_NAME "SsLabs"
#define BRAND_PRODUCT_NAME "Svid Desktop"
#define BRAND_FILE_DESCRIPTION "Svid Desktop"
#define BRAND_COPYRIGHT "Copyright (C) 2026 Bui Xuan Mai. All rights reserved."
#define BRAND_PUBLISHER "Svid"
#define BRAND_DARK_BG_R 10
#define BRAND_DARK_BG_G 8
#define BRAND_DARK_BG_B 9
#define BRAND_LIGHT_BG_R 252
#define BRAND_LIGHT_BG_G 249
#define BRAND_LIGHT_BG_B 247
#define BRAND_DEFAULT_DARK 1

#endif  // BRAND_CONFIG_H_
HEADER
fi
echo "  Windows: brand_config.h generated"

# === LICENSE file: brand-aware ===
LICENSE_FILE="$ROOT_DIR/LICENSE"
if [[ "$BRAND" == "vidcombo" ]]; then
  cat > "$LICENSE_FILE" << 'LICENSE_EOF'
MIT License

Copyright © 2026 VidCombo

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
LICENSE_EOF
else
  cat > "$LICENSE_FILE" << 'LICENSE_EOF'
MIT License

Copyright © 2026 Svid

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
LICENSE_EOF
fi
echo "  LICENSE file updated for $BRAND"

# === Windows: Copy brand-specific app icon ===
BRAND_WIN_ICON="$ROOT_DIR/assets/brands/$BRAND/app_icon.ico"
WIN_ICON="$ROOT_DIR/windows/runner/resources/app_icon.ico"
if [[ ! -f "$BRAND_WIN_ICON" ]]; then
  echo "  ERROR: missing Windows app icon: $BRAND_WIN_ICON" >&2
  exit 1
fi
cp "$BRAND_WIN_ICON" "$WIN_ICON"
if ! cmp -s "$BRAND_WIN_ICON" "$WIN_ICON"; then
  echo "  ERROR: Windows runner icon does not match brands/$BRAND/app_icon.ico after copy" >&2
  exit 1
fi
echo "  Windows: app_icon.ico copied from brands/$BRAND/ and verified"

# === Linux: Copy brand-specific app icon ===
BRAND_LINUX_ICON="$ROOT_DIR/assets/brands/$BRAND/app_icon.png"
LINUX_ICON="$ROOT_DIR/linux/icons/app_icon.png"
if [[ -f "$BRAND_LINUX_ICON" ]]; then
  mkdir -p "$(dirname "$LINUX_ICON")"
  cp "$BRAND_LINUX_ICON" "$LINUX_ICON"
  echo "  Linux: app_icon.png copied from brands/$BRAND/"
fi

# === Linux: Update CMakeLists.txt BINARY_NAME + PRODUCT_DISPLAY_NAME + APPLICATION_ID + BRAND_NAME_LOWER ===
LINUX_CMAKE="$ROOT_DIR/linux/CMakeLists.txt"
if [[ -f "$LINUX_CMAKE" ]]; then
  if [[ "$BRAND" == "vidcombo" ]]; then
    sedi 's/set(BINARY_NAME "svid")/set(BINARY_NAME "vidcombo")/' "$LINUX_CMAKE" 2>/dev/null || true
    sedi 's/set(PRODUCT_DISPLAY_NAME "Svid")/set(PRODUCT_DISPLAY_NAME "VidCombo")/' "$LINUX_CMAKE" 2>/dev/null || true
    sedi 's/set(APPLICATION_ID "com.svid.app")/set(APPLICATION_ID "com.tinasoft.vidcombo")/' "$LINUX_CMAKE" 2>/dev/null || true
    sedi 's/set(BRAND_NAME_LOWER "svid")/set(BRAND_NAME_LOWER "vidcombo")/' "$LINUX_CMAKE" 2>/dev/null || true
  else
    sedi 's/set(BINARY_NAME "vidcombo")/set(BINARY_NAME "svid")/' "$LINUX_CMAKE" 2>/dev/null || true
    sedi 's/set(PRODUCT_DISPLAY_NAME "VidCombo")/set(PRODUCT_DISPLAY_NAME "Svid")/' "$LINUX_CMAKE" 2>/dev/null || true
    sedi 's/set(APPLICATION_ID "com.tinasoft.vidcombo")/set(APPLICATION_ID "com.svid.app")/' "$LINUX_CMAKE" 2>/dev/null || true
    sedi 's/set(BRAND_NAME_LOWER "vidcombo")/set(BRAND_NAME_LOWER "svid")/' "$LINUX_CMAKE" 2>/dev/null || true
  fi
  echo "  Linux: CMakeLists.txt BINARY_NAME + PRODUCT_DISPLAY_NAME + APPLICATION_ID updated"
fi

echo ""
echo "Brand set to: $BRAND"
echo "Build commands:"
echo "  macOS:   fvm flutter build macos --dart-define=BRAND=$BRAND"
echo "  Windows: flutter build windows --dart-define=BRAND=$BRAND"
echo "  Linux:   flutter build linux --dart-define=BRAND=$BRAND"
echo "  Package: bash scripts/package_linux.sh $BRAND"
