// Brand configuration for Windows build — Svid (default)
// Generated by scripts/set_brand.sh

#ifndef BRAND_CONFIG_H_
#define BRAND_CONFIG_H_

#define BRAND_NAME "Svid"
#define BRAND_NAME_LOWER "svid"
#define BRAND_NAME_WIDE L"Svid"
#define BRAND_WINDOW_CLASS_NAME L"Svid_WIN32_WINDOW"
#define BRAND_EXE_NAME "svid.exe"
#define BRAND_URL_SCHEME "svid://"
#define BRAND_BUNDLE_ID "com.svid.app"
#define BRAND_APP_USER_MODEL_ID L"com.svid.app"
#define BRAND_COMPANY_NAME "Bui Xuan Mai"
#define BRAND_PRODUCT_NAME "Svid Desktop"
#define BRAND_FILE_DESCRIPTION "Svid Desktop"
#define BRAND_COPYRIGHT "Copyright (C) 2026 Bui Xuan Mai. All rights reserved."
#define BRAND_PUBLISHER "Svid"
#define BRAND_DARK_BG_R 10
#define BRAND_DARK_BG_G 8
#define BRAND_DARK_BG_B 9
#define BRAND_LIGHT_BG_R 252
#define BRAND_LIGHT_BG_G 249
#define BRAND_LIGHT_BG_B 247
#define BRAND_DEFAULT_DARK 1

#endif  // BRAND_CONFIG_H_
