// Brand configuration for Windows build — SSvid (default)
// Generated by scripts/set_brand.sh

#ifndef BRAND_CONFIG_H_
#define BRAND_CONFIG_H_

#define BRAND_NAME "SSvid"
#define BRAND_NAME_LOWER "ssvid"
#define BRAND_NAME_WIDE L"SSvid"
#define BRAND_WINDOW_CLASS_NAME L"SSvid_WIN32_WINDOW"
#define BRAND_EXE_NAME "ssvid.exe"
#define BRAND_URL_SCHEME "ssvid://"
#define BRAND_BUNDLE_ID "com.ssvid.app"
#define BRAND_APP_USER_MODEL_ID L"com.ssvid.app"
#define BRAND_COMPANY_NAME "Bui Xuan Mai"
#define BRAND_PRODUCT_NAME "SSvid Desktop"
#define BRAND_FILE_DESCRIPTION "SSvid Desktop"
#define BRAND_COPYRIGHT "Copyright (C) 2026 Bui Xuan Mai. All rights reserved."
#define BRAND_PUBLISHER "SSvid"
#define BRAND_DARK_BG_R 10
#define BRAND_DARK_BG_G 8
#define BRAND_DARK_BG_B 9
#define BRAND_LIGHT_BG_R 252
#define BRAND_LIGHT_BG_G 249
#define BRAND_LIGHT_BG_B 247
#define BRAND_DEFAULT_DARK 1

#endif  // BRAND_CONFIG_H_
